### ISSUE TITLE
Command to paste clipboard

### ISSUE THREAD

**Issue by msx80** [commanderx16/x16-emulator#10]
It would be great to be able to paste the content of the clipboard into the emulator, like to copy/paste basic programs or such. Text would be entered like if it was typed.

Perhaps with a right mouse button click, like in Putty.

**Comment by paulscottrobson** [comment]
Paste is doable. SDL can access the clipboard, presumably it works cross platform. Can convert ASCII to scancodes and push them in the queue. Cut is harder. A simpler solution would be to rip and decode the BASIC from the memory dump.

**Comment by mist64** [comment]
For "cut", how about a mode that can be enabled though the command line that hooks $FFD2 (BSOUT; just like we already hook $FFD5/FFD8 for LOAD/SAVE) and also prints the character to the hosts's stdout?

**Comment by paulscottrobson** [comment]
Yes, that would have the advantage of being forward compatible. One way to do the clipboard would be just to write a script that tokenises ASCII code, and then autoload it. There probably are several C64 utilities that do this already, but unless they access the token table in the ROM (assuming it hasn't moved !) it won't work for the additions.

**Comment by msx80** [comment]
My request was only for "paste", but any kind of "copy" even rudimentary like a txt dump of what's on screen, would be welcome too!

**Comment by rsbohn** [comment]
You could put the clipboard on an IEC device (7 perhaps). Is there any way to have BASIC read source from a file, or have the keyboard read from a device?

**Comment by rsbohn** [comment]
I guess that would require a restructure of the sdcard/iec bus code. :(

**Comment by paulscottrobson** [comment]
The simplest is to convert it to a .PRG and load it in via that method. It would be possible to hack the key input routine to 'type' it in, in the same way the Ohio Scientific computers worked. PRG conversion is far more efficient.

**Comment by oziphantom** [comment]
For assistance it is worth noting that VICE does this, so you could look at its SDL code. However it only does paste and not copy from, this is not a trivial problem, as where do you want to paste it? if its back into the emulator then it should copy it as PETSCII, however if you then expect to copy it into a text file on the host, then it needs to be converted to ASCII... which method do you use to convert? how do you know when to make it ASCII or PETSCII... x16 doesn't have to handle different machines which is helpful. For ASCII -> PETSCII conversion VICE ships with 'petcat'

**Comment by msx80** [comment]
please let's keep it simple :) hacking in a new IEC device is the opposite of simple, also it would only work for loading in programs or files. For that we already have ways (simply save the file in the mapped folder for example).

This is just to "paste" text from the clipboard into the emulator as if it was typed, exacly like the right mouse button on Putty or Vice. That way you can copy paste Basic snippet but also command lines, strings you have to input into any running program (like spreadsheets or word processors) etc.

Code would be as follow:

- For each character in clipboard string:
- transform it appropriately (ascii to petscii or anything that's needed, i'm sure such procedure is already in the program).
- feed it to the input system as if it were typed.
- end

Nothing more, nothing less :)

Cut (actually copy) is harder and can be added someway later, but i think a quick paste option would be super useful (and easy to implement).

**Comment by mist64** [comment]
In e22d73c, I have added the -bas command line argument that injects an ASCII file into the keyboard.

**Comment by mist64** [comment]
In 968a1b7, I've added pasting using Cmd + V.

**Comment by mist64** [comment]
Added echo mode in 5eb2a60.

Do we now have the complete feature set? :)

**Comment by mist64** [comment]
Now also documented in the README: c87ad6a

**Comment by paulscottrobson** [comment]
I'll shift the makeprg to another repository or it'll keep coming back :)
