### ISSUE TITLE
File I/O Problems

### ISSUE THREAD

**Issue by MCPEmaniac** [commanderx16/x16-emulator#101]
The following program prints a ? and then freezes the emulator.
10 OPEN 1,8,2,"TESTDATA"
20 PRINT# 1,5
30 CLOSE 1

I also tried the following which works with my C64 and 1541 where S is for sequential and W is for write.
10 OPEN 1,8,2,"O:TESTDATA,S,W"

I can do an OPEN followed immediately by a CLOSE on the emulator, but when I put a PRINT# between the OPEN and CLOSE the emulator freezes.

Does the emulator not currently support file I/O? I assume device number 8 will place the file in the directory where the emulator is started. Is this correct?

**Comment by greg-king5** [comment]
Devices are different between Commander X16 and Commodore computers.  The X16 has no Datasette (tape) and devices 8 and 9 are an SD card.  The emulator puts the host's file-system on device 1.

**Comment by MCPEmaniac** [comment]
Ok, but the program above should still not freeze the emulator. The only way I could recover was to kill the emulator. Also, when I change the device number in line 10 above from 8 to 1 I get the error message "?ILLEGAL DEVICE NUMBER ERROR IN 10".

I thought I read somewhere that Commander X16 was 100% compatible with Commodore 64 BASIC, but there appears to be exceptions to this generalization.

**Comment by greg-king5** [comment]
They never claimed to be 100% compatible with the entire C64.

See also #104.

**Comment by mist64** [comment]
The originally stated BASIC program is supposed to work on the X16 – if you have an SD card attached. In the emulator, thats with `-sdcard`.

It doesn't currently work though, because the SD card driver is read-only.

We should at least not freeze, but return a "WRITE PROTECT ERROR".

**Comment by mist64** [comment]
Fixed by e84dc1b24044c0daea7eb45f044a14bf68612fc9
