### ISSUE TITLE
[BUG] BCD does not work

### ISSUE THREAD

**Issue by qbradq** [commanderx16/x16-emulator#102]
Binary Coded Decimal mode does not work in the emulator.

### Version Information
First noticed on a build compiled from 9890e9aba7be374e89d5639ed5821bfaa9fb5abf
Verified still reproducible on 6bf9d9e40ac6ea7fe7ef1aa63642a7a0934fffb2

### Test Case
Machine code program that attempts to calculate `17+15=32` using BCD.
```
sed
lda #$17
adc #$15
sta $b000
cld
rts
```

A BASIC program that injects the above ML program into $a000, executes it, and prints the results:

```
10 DATA 248,169,23,105,21,141,0,176,216,96
100 FOR I=0 TO 9
110 READ BT
120 POKE $A000+I,BT
130 NEXT
140 POKE $B000,0
150 SYS $A000
160 BT=PEEK($B000)
170 PRINT"17+15=";BT;"EXPECTED 50"
```

Example execution:
![Image of Results](http://imgur.com/0qgziFgl.png)

### Additional context
This is a problem for me because BCD is used for the fastest constant-time base 10 conversion routine for 6502. This code snippet is from http://www.obelisk.me.uk/6502/algorithms.html but the algorithm has been published all over.

```
; Convert an 16 bit binary value into a 24bit BCD value
BIN2BCD LDA #0          ;Clear the result area
        STA RES+0
        STA RES+1
        STA RES+2
        LDX #16         ;Setup the bit counter
        SED             ;Enter decimal mode
_LOOP   ASL VAL+0       ;Shift a bit out of the binary
        ROL VAL+1       ;... value
        LDA RES+0       ;And add it into the result, doubling
        ADC RES+0       ;... it at the same time
        STA RES+0
        LDA RES+1
        ADC RES+1
        STA RES+1
        LDA RES+2
        ADC RES+2
        STA RES+2
        DEX             ;More bits to process?
        BNE _LOOP
        CLD             ;Leave decimal mode
```

BCD should be supported on the real hardware per the WDC datasheet https://www.westerndesigncenter.com/wdc/documentation/w65c02s.pdf

BCD mode can be disabled in the source code, but it is not: https://github.com/commanderx16/x16-emulator/blob/d44dfad605ef89271be012e9cb4646a1978d49aa/cpu/fake6502.c#L113-L116

BCD is implemented in two places:
ADC
https://github.com/commanderx16/x16-emulator/blob/ac46b2a91926aeff63c18f93f46054646689865d/cpu/instructions.h#L17-L47
SBC
https://github.com/commanderx16/x16-emulator/blob/ac46b2a91926aeff63c18f93f46054646689865d/cpu/instructions.h#L396-L427

**Comment by mist64** [comment]
Confirmed.

<img width="1306" alt="Screen Shot 2019-09-22 at 20 23 07" src="https://user-images.githubusercontent.com/869384/65392599-de7b1b00-dd76-11e9-9739-7d911932ab01.png">

**Comment by jeriesar94** [comment]
@mist64 , do you think this might be the problem? as we are still loading the rom binary image to the emulator. 

I believe the problem is in this highlighted "CLD" line:

![image](https://user-images.githubusercontent.com/32031587/65393668-3ff9b480-dd8c-11e9-8a0c-db344d2faaa2.png)

**Comment by qbradq** [comment]
BCD is still not working 100% correctly. I am still trying to figure out exactly what's going wrong, but the debugger seems to be resetting the decimal flag and that's not helping :)

Here is the BCD2BIN conversion routine running correctly on the C64
![](http://i.imgur.com/NKGFhsc.png)
![](http://imgur.com/bZt8Gdql.png)
Note the BCD string `000256` at $2000-$2002

And here is the same exercise on the X16
x16-emulator commit 6812fe4e091970a01e0e772cf6c9a3201a40f401
x16-rom commit 8b1f368435848b607f3e939c85da295e83441167
![](http://imgur.com/GbeWAzFl.png)
Note the BCD string `000000` at $2000-$2002

**Comment by qbradq** [comment]
There appears to be a few corner-cases in BCD that are not working. One in particular creates the above behavior. I have simplified the test case to display the incorrect results:

![](http://imgur.com/gMtB3U3l.png)
Correct Result @$2000: 9+6=15
Incorrect Result @$2001: 9+7=10

**Comment by greg-king5** [comment]
The use-case's name is `BIN2BCD`, not `BCD2BIN`.

The second `ASL` must be `ROL`.
