### ISSUE TITLE
[Feature Request] Intercept OPEN and other I/O on Device 1, not just SAVE and LOAD

### ISSUE THREAD

**Issue by thylordroot** [commanderx16/x16-emulator#104]
Currently, the emulator does not seem to support using OPEN on Device 1, which is currently supported by LOAD and SAVE. Instead, it returns error 9 (Device Error) as it would on the real system. In the emulator, Device 1 is allocated to the host directory where the emulator is located. Assume that X,Y contains a pointer to a path string and A its length. To reproduce this issue, use the following code:

~~~~
jsr $ffbd ; setnam 
lda #$01 ; Logical file is 1
ldx #$01 ; Device is 1
ldy #$00 ; Subcommand is 0
jsr $ffba ; setlfs
jfs $ffc0 ; open
~~~~

On the Facebook page, it has been suggested that we should be using the SD card mounting option instead, so this is therefore a feature request instead of a bug. I believe that this behavior should be maintained for orthogonality since for the purposes of LOAD and SAVE, Device 1 takes on special meaning in the emulator. By generically supporting this functionality, it means that this association is maintained.

In addition to OPEN, the following system calls may also need to be intercepted:

* CHRIN
* CHROUT
* CLOSE
* CLALL

**Comment by greg-king5** [comment]
Nevermind orthogonality.  The best reason is simply that it's more practical.  We wouldn't need to spend time importing and exporting our files to and from SD card images.

**Comment by kghultland** [comment]
Yeah, this would be a great change. As I have no SD card reader on my stationary computer I have problems creating an image file.  I tried using Win32 Disk Imager but it only allows me to create an image from a USB stick and the smallest I have is 64 GB and somehow I get a feeling that it will be too large :D

**Comment by mist64** [comment]
Commit e84dc1b allows all KERNAL APIs that work with the SD card to also work with the host filesystem, including KERNAL `SETNAM`, `SETLFS`, `OPEN` etc. and BASIC `OPEN`, `GET#`, `PRINT#`.
