### ISSUE TITLE
-keymap nordic should probably be changed to sv-se

### ISSUE THREAD

**Issue by mobluse** [commanderx16/x16-emulator#107]
In x16emu when you press F9 sv-se exists (and not nordic), but when you use the option -keymap nordic exists (and not sv-se). It is more correct to call it sv-se than nordic since when you press Ctrl+O it is compatible with Swedish, but not e.g. Danish or Norwegian. Swedish and Finnish are the same when it comes to what is printed on most keyboards, but AltGr for unmarked keys can be different. I think also Danish and Norwegian should be supported. Before, when only PETSCII was supported, nordic was enough since the Nordic keyboards agreed on PETSCII characters' positions.

**Comment by akshaygamb** [comment]
Thanks

**Comment by mist64** [comment]
I have a branch here: https://github.com/commanderx16/x16-rom/tree/compressed_keymaps

I hope I can get it  into r32. It'll reintroduce Swedish, Finnish, Norwegian and Danish.

**Comment by mobluse** [comment]
`x16emu -keymap sv` now works.
