### ISSUE TITLE
Add autostart/autoend facilities.

### ISSUE THREAD

**Issue by paulscottrobson** [commanderx16/x16-emulator#11]
Rationale : to run machine code programs directly from the command line without going via MONITOR or SYS.

First option, called (say) -run executes the machine code .PRG program loaded at its start address.

Parallel to this, adopt an unused opcode as an exit-and-dump memory operation code.

(I rigged something like this to test the 65C02 opcodes)

**Comment by rsbohn** [comment]
This would allow for automated testing of the emulator. Very good idea! We could then have a test suite for basic operations, reading and writing the 'dataset', reading and writing an SD card image, etc.

**Comment by mist64** [comment]
Autostart implemented here: a87d6f8

**Comment by mist64** [comment]
Autoend with save implemented here: 5414832
