### ISSUE TITLE
Emulator speed compared to real HW

### ISSUE THREAD

**Issue by JimmyDansbo** [commanderx16/x16-emulator#118]
Would it be possible to make the emulator run at the same speed as the real hardware? Maybe switching speeds or at least give some sort of indication of the speed compared to the real hardware.
I ask because it would be a shame to have developed software that runs fine in the emulator, but too slow on the real hardware or the other way round.
Thank you for your great work.

**Comment by mist64** [comment]
The emulator never runs faster than real hardware, but it may run slower. Once every 5 seconds, we should append the current speed to the window title if it's below 100%: "Commander X 16 (80%)"
