### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by paulscottrobson** [commanderx16/x16-emulator#12]
Add a debugger to the emulator.

Replace the main execution loop with a state machine or similar, then add a direct interface to allow single stepping, step over, memory access, breakpoints and so on. Add a 65C02 pseudo-operation to breakpoint automatically. In debug state display CPU registers , memory and so on.

**Comment by oziphantom** [comment]
why not just use the actual 65C02 instruction BRK to err Break?

**Comment by paulscottrobson** [comment]
Two reasons. Firstly, you're relying on the thing you are debugging working. BRK itself is a classic example. How do you debug it. TIM is fine, but not suitable for heavyweight debugging work. I'm thinking of some like this https://www.youtube.com/watch?v=1m0MgE33CXw - probably not quite this jazzy initially.

**Comment by oziphantom** [comment]
you are stuck in a local minima, if you want to interrupt the machine and get back control to enter a monitor then you have a hot key which "does a freeze" and thus drops you into a "emulator's monitor", if you want code to automatically enter this monitor when you hit a brk, as its a "demons be here" catch case in your code, you choose the option in a menu to enter into the emulators monitor when a brk in executed. If you want to have actual breakpoints then you get the emulator's monitor to have breakpoints that don't need to change or modify the host machines memory state. Having the code hand over to the emulators monitor is not something you would do very often and is to catch the code going wrong, the correct way is to have the emulators monitor have a proper breakpoint system.

**Comment by paulscottrobson** [comment]
Yes, that's what I would like to do. It's not my project. TIM is fine for local debugging on the real machine (though it could be improved), but the emulator should have one that exists purely in its virtual space.

**Comment by mist64** [comment]
Merged.
