### ISSUE TITLE
[WebAssembly] Audio support missing

### ISSUE THREAD

**Issue by sebastianvog** [commanderx16/x16-emulator#122]
Sounds doesn't currently work with WebAssembly (compiled with WITH_YM2151) 

I plan to look into it  , but would like to open this up for any feedback or suggestions  from anyone who might already  tried or has experience with it . @Frank-Buss maybe :-)

Links for emscripten sound support:
https://emscripten.org/docs/porting/Audio.html

From the emscripten FAQ:
What are my options for audio playback?
Emscripten has partial support for SDL1 and 2 audio, and OpenAL.

To use SDL1 audio, include it as #include <SDL/SDL_mixer.h>. You can use it that way alongside SDL1, SDL2, or another library for platform integration.

To use SDL2 audio, include it as #include <SDL2/SDL_mixer.h> and use -s USE_SDL_MIXER=2. Format support is currently limited to OGG and WAV.

and maybe this discussion helps:
https://github.com/emscripten-core/emscripten/issues/3477

and general for chrome
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

**Comment by sebastianvog** [comment]
After a bit of research (aka google and trial and error) I got some audio out. I should have a PR for at least an experimental version (only if WITH_YM2151 defined during compilation) this weekend. Chrome works ok, FireFox with lag, Safari doesn't support AudioContext. I have not tried mobile browsers.
I have a prototype up on https://sebastianvog.github.io/x16-emulator/x16emu.html
(select the audio.prg from @Frank-Buss  in the "Select Program" dropdown)

I don't have any other files for testing, if there are more samples or basic programs please let me know.

**Comment by Frank-Buss** [comment]
Looks good, works here in Linux and with Chrome.
I have 2 BASIC examples:
https://gist.github.com/Frank-Buss/b9a37249d32d3cbdeff29433bcd4bba8
https://gist.github.com/Frank-Buss/1066eaaf8b0e2a718fcf38bf64a6ce2e
But the 2 addresses $9FE0 and $9FE1 needs to be swapped, will work after my new PR is merged. But for testing, you can just swap it in the BASIC program. I just tested the gong and it works.

**Comment by Frank-Buss** [comment]
PS: mode7 demo is broken, at least on Linux with Chrome, and the Maze BASIC example sometimes says "syntax error in 310" for maze type 3, and sometimes "illegal quantity error in 310" for maze type 2. But not in the native C emulator on Linux.
![emulator](https://user-images.githubusercontent.com/55055211/65612333-5f732600-dfb4-11e9-8b09-24662ceda244.png)
