### ISSUE TITLE
white is not white

### ISSUE THREAD

**Issue by Schlowski** [commanderx16/x16-emulator#124]
4bitRGB color $FFF is converted to 8bitRGB color $F0F0F0 which is a light gray.

Color conversion should simply copy the original 4 bit into low and high nibble.

$0 -> $00
$1 -> $11
$2 -> $22
...
$E -> $EE
$F -> $FF

**Comment by rnentjes** [comment]
Good catch, quick test shows the difference:

![image](https://user-images.githubusercontent.com/553168/65607648-2aafa080-dfad-11e9-9ac9-a6dbf15027cd.png)

I'll submit a pull request.
