### ISSUE TITLE
Z-Depth in sprite does not work

### ISSUE THREAD

**Issue by Schlowski** [commanderx16/x16-emulator#132]
Independent of Z-Depth setting in sprite register 6 sprites will always be drawn on top of all layers.

**Comment by mist64** [comment]
Yes, this is not yet implemented. Shouldn't be too hard though. :)

**Comment by mist64** [comment]
Should be fixed since 91de8ce. Can you try?

**Comment by Schlowski** [comment]
Sorry, I can't compile the emulator :-(

**Comment by mist64** [comment]
Do you have a test program I can try?

**Comment by Schlowski** [comment]
[SPRITETEST.zip](https://github.com/commanderx16/x16-emulator/files/3665749/SPRITETEST.zip)
This sprite should be below the text.
GOSUB 500 sets Z-DEPTH to 1
GOSUB 520 sets Z-DEPTH to 2
GOSUB 540 sets Z-DEPTH to 3

Load, list and run

![SpriteError](https://user-images.githubusercontent.com/3668551/65819611-df042d80-e21e-11e9-9424-08d2425420e9.png)

**Comment by mist64** [comment]
Works now. The difference between 1 and 2 is visible using `POKE 646,1` and drawing characters over the sprite.
