### ISSUE TITLE
Tile scrolling is no longer working.

### ISSUE THREAD

**Issue by jjbliss** [commanderx16/x16-emulator#142]
As of commit 91de8cedef295018ce5aaad29ee408f6d08ac47c, tile scrolling seems to have stopped working.

My code that this has stopped working for has set layer 0 to mode 4.  changing H_SCROLL and V_SCROLL is not doing anything.

**Comment by mist64** [comment]
Do you have test code I can try it with?

**Comment by jjbliss** [comment]
I have an earlier version of the code that I'm working on that should demonstrate the issue decently without complicating things too much.

If you'd prefer, I could try to put together a smaller example to demonstrate the issue, but that will take a bit of time.

here is a video of how it previously behaved:
https://www.youtube.com/watch?v=S2fR4Fe4nyw

Now the tiles do not scroll at all.

I've attached a zip of the code.
Sorry it's a bit of a mess.
the prg file is already there, but running make should also work, it's assembled with acme. 
I've been running it with "./x16emu -prg test.prg -run"
[bliss-x16.zip](https://github.com/commanderx16/x16-emulator/files/3665802/bliss-x16.zip)

The main assembly file is test.asm

Actually setting the scroll values is done in tile.asm like this.
.set_layer_0_hscroll:
  +VERA_SET_ADDR VRAM_layer0+6,1
  lda X_SCROLL
  sta VERA_data
  lda X_SCROLL+1
  and #$0F
  sta VERA_data
  rts

**Comment by jjbliss** [comment]
Also, it is very obvious on https://github.com/indigodarkwolf/x16-racer.
Running on r32 works fine, but current build does not work properly.

**Comment by mist64** [comment]
Fixed in 3bc0795
