### ISSUE TITLE
[BUG] BCD Incorrect Function

### ISSUE THREAD

**Issue by qbradq** [commanderx16/x16-emulator#147]
There appears to be a few corner-cases in BCD that are not working. Here is a small test program:

![](http://imgur.com/gMtB3U3l.png)
Correct Result @$2000: 9+6=15
Incorrect Result @$2001: 9+7=10

_Originally posted by @qbradq in https://github.com/commanderx16/x16-emulator/issues/102#issuecomment-536306795_

**Comment by mist64** [comment]
See also #145.

**Comment by qbradq** [comment]
Test runs with latest commit:
![](http://imgur.com/YnOGvxtl.png)

It should be OK to merge now, however I have not tested the code path with NES_CPU defined.

**Comment by qbradq** [comment]
Fixed in #148
