### ISSUE TITLE
[Feature Request] Command within the Emulator to terminate the emulator

### ISSUE THREAD

**Issue by crb02005** [commanderx16/x16-emulator#151]
I would like a command within the emulator which could terminate the emulator.

**Comment by mist64** [comment]
JMP $FFFF does it

**Comment by greg-king5** [comment]
And in BASIC: `SYS$FFFF`

**Comment by greg-king5** [comment]
However, they do create a debugging file named "dump.bin" in the current directory.

**Comment by crb02005** [comment]
Works great thanks!
