### ISSUE TITLE
Wrong VIA ports?

### ISSUE THREAD

**Issue by Schlowski** [commanderx16/x16-emulator#155]
The Programmers Referance Guide lists the VIA#1 for the bankswitch registers as follows:

VIA#1

Pin	Description
PA0-7	RAM bank
PB0-2	ROM bank
PB3-7	[TBD]

This leads to the assumption, that $9F60 is the port for the RAM bank and $9F61 the port for the ROM bank.

In the emulator the RAM bank switch is definately $9F61, the following little program show this:

10 GOSUB200
100 PRINT"BANK # (-1=QUIT)";:INPUTB
110 IFB<0THENRETURN
120 IFB>255THENEND
130 POKE$9F61,B
140 PRINT"BANK #";B;"=";PEEK($A000):PRINT
150 GOTO100
200 REM MARK RAM BANKS WITH #
210 FORB=0TO255
220 POKE$9F61,B
230 POKE$A000,B
240 NEXT
250 POKE$9F61,0
260 RETURN

Switch to $9F60 and the emulator crashes...

Question is: Documentation error or emulator error?

**Comment by mist64** [comment]
In the VIA specification, PA is register 1 and PB is register 0, so this is correct.

But yes, the documentation should also have the addresses.

**Comment by Schlowski** [comment]
Oh, didn't know that, thx!

**Comment by mist64** [comment]
Reopening to track the documentation problem.

**Comment by mist64** [comment]
The documentation actually already states the addresses:

> The RAM bank (0-255) defaults to 255, and the ROM bank (0-7) defaults to 7 on RESET. The RAM bank can be configured through VIA#1 PA0-7 ($9F61), and the ROM bank through VIA#1 PB0-2 ($9F60). See section "I/O Programming" for more information.
