### ISSUE TITLE
-run fault

### ISSUE THREAD

**Issue by paulscottrobson** [commanderx16/x16-emulator#159]
If you write an assembler file with multiple origins e.g.

*=$F00
jmp start
* = $1000
start: ... do stuff

It doesn't work when you run it using -prg -run. However if in the run_after_load code around 850 you replace the \r with \n in the snprintf() it works.

No idea why !

**Comment by mist64** [comment]
Do you have a minimal test asm file? ca65 or acme?

**Comment by paulscottrobson** [comment]
Misdiagnosis. Appears to be a load address issue. Attached zip is for 64tass but it doesn't make any difference., it's 3 bytes :) Loading to $2000 works, loading to $1FFC doesn't. 

./x16emu -debug -prg test.prg -run .... does or doesn't depending on the origin in the assembler.

[prg_fail.zip](https://github.com/commanderx16/x16-emulator/files/3686851/prg_fail.zip)

**Comment by paulscottrobson** [comment]
Duplicate of #139 and almost certainly the same problem, casing SYS which explains why $FF0 and $A000 don't work and $1000 does :)
