### ISSUE TITLE
Replacement of usleep()

### ISSUE THREAD

**Issue by paulscottrobson** [commanderx16/x16-emulator#16]
In the main loop, there is a usleep(20000) which synchronises the IRQ and speed. It may be better to synchronise this to a clock (could use SDL_Ticks) rather than just stop,(assuming video update isn't in another thread) to free up time for Video rendering. It would also allow us to have automatic frame skipping which would allow the sprite limitation to rise.

**Comment by mist64** [comment]
I agree this is a much better design. I don't have any experience with SDL_Ticks though, do you?

**Comment by paulscottrobson** [comment]
Some. I have an emulator Framework I use which has syncing built in. I suspect on some platforms the resolution isn't fabulous, but it's probably good enough.
