### ISSUE TITLE
Cannot switch mode in Assembler

### ISSUE THREAD

**Issue by paulscottrobson** [commanderx16/x16-emulator#164]
SYS $FF5F, or jsr $FF5F doesn't work in Assembler running from the cli, the space contains $AA. Presume this is a vector not being copied ?

**Comment by rsbohn12** [comment]
Machine language programs started with "SYS" will have the BASIC ROM mapped at $C000-$FFFF and have to write #7 to $9F61 to switch to the KERNAL ROM. The KERNAL API $FF81+ is supported both from the BASIC ROM and the KERNAL ROM, but it's faster from the KERNAL ROM, and the extended API is only available from the KERNAL ROM.

Is $FF5F part of the extended API?

Also it seems the ROM from a SYS call is bank 4 (GEOS), not bank 0 (BASIC).

```
begin:
	lda V1PB
	tax
	lda #0
	sta V1PB
	jsr HEXOUT
	lda #$0D
	jsr CHROUT
	txa
	sta V1PB
	rts
```
[mixup.txt](https://github.com/commanderx16/x16-emulator/files/3702789/mixup.txt)

**Comment by mist64** [comment]
The docs were wrong, bank 4 is BASIC. This file is always right: https://github.com/commanderx16/x16-rom/blob/master/banks.inc

**Comment by mist64** [comment]
Docs were fixed in https://github.com/commanderx16/x16-docs/commit/7d4ef451da9fdb7a6bde81601853c6a6a15c2ad1

**Comment by mist64** [comment]
@paulscottrobson As for the original issue, this was fixed in https://github.com/commanderx16/x16-rom/commit/d35aa0865be843ca5472cb698cd163e0ccd4363d which will be released as part of r33.
