### ISSUE TITLE
POKE and VERA

### ISSUE THREAD

**Issue by tomxp411** [commanderx16/x16-emulator#171]
I noticed something David said in the FB group about the 65C02 and the POKE statement when used with VERA. Specifically, on real hardware, using POKE to write to VERA will cause different behavior on the emulator and on real hardware.

I think what David said (I can't find the reference) is that the BASIC POKE command uses **STA ($xxxx),Y** (Indirect Indexed) to write to the POKE address, and this actually triggers a _read_ of the address before writing to that address. This would cause VERA to advance the memory pointer once before the memory write, then write to the next address, then advance the pointer again. As a result, data will be written to the wrong address, and VERA will have advanced the memory pointer twice, instead of once. 

While the ideal solution would be to use a different addressing mode that does not cause an errant read from VERA, the emulator should also be modified so that the indirect writes behave the same way on the emulator as they do on real hardware. 

This seems like too critical a thing to miss getting right in the emulator, and any instructions that cause the CPU to access a VERA register more than once per instruction should have the same effect in the emulator as on the real machine. 

As an aside, I'd be interested to know why this is happening. Does this happen on all indexed modes, or just indirect indexed?

**Comment by mist64** [comment]
I am pretty sure this is happens only on the NMOS 6502, not the CMOS 65C02.

**Comment by tomxp411** [comment]
If that's the case, then that's great. Maybe it's something someone with the real hardware can confirm, in which case this issue could be closed with no action.

**Comment by mist64** [comment]
BASIC & KERNEL run fine on real hardware. :)

**Comment by tomxp411** [comment]
Thanks. If that's not a problem on the 65C02, that's great. 

For reference, this is the kind of thing that was being discussed:

10 POKE $9F22,32
50 FOR Y=0 TO 59
60 POKE $9F21,Y
80 POKE $9F20,0
90 FOR X=0 TO 79
100 POKE $9F23,0
110 NEXT
120 NEXT

David says: "FYI - this won't work on the real hardware ... the POKE command will do a read before a write, this causing an extra increment. This  is actually a quirk of the 6502 CPU and the way 6502 implements the command, which is not emulated by our emulator just now."

**Comment by tomxp411** [comment]
@mist64 I've confirmed that the the data sheet for the 65C02 says "this cycle contains invalid addresses", and that this is still a 6 cycle operation on the 65C02. 

The fix is to simply change the STA (poker),Z in the POKE subroutine to STA (poker). However, this is the wrong project to fix that, since my original intent here was to reproduce the 6 and 7 cycle behavior of the instruction in the emulator. I'll open an issue (and try to submit a patch) in the ROM Git. 

This can remain closed, since after patching the ROM, this behavior does not need to be altered in the emulator.
