### ISSUE TITLE
Echo works erratically when turning it off and then back on

### ISSUE THREAD

**Issue by MCPEmaniac** [commanderx16/x16-emulator#174]
The -echo option works erratically when turning it off and back on using address $9FB3. Sometimes it doesn't echo anything, and at other times it echos everything on the same terminal line instead of separate terminal lines.

The following program demonstrates the problem when the emulator is started with the "-echo" option. Even though there are two list statements with echo turned on, when the program is run the program is only listed a single time. When the following program is started with the "-echo raw" option all lines of the program are output to the same terminal line.

10 X=PEEK($9FB3):PRINT X
20 PRINT "A":LIST
30 POKE $9FB3,0
40 POKE $9FB3,X
50 PRINT "B":LIST

My sprite editor program turns echo off at the start and turns it back on temporarily only when exporting sprite data. I took this approach so the terminal wouldn't have a lot of irrelevant garbage data mixed with the sprite data. This approach worked with R32 but now seems to be broken with R33. With R33 all lines of my output are echoed on the same terminal line whereas with R32 each line of my output was output to a separate terminal line. I include a "\n" between each line of my output.

I noticed after "manually" poking $9FB3 with the value 2 (which I believe is associated with the "-echo" option) or the value 3 (which I believe is associated with the "-echo iso" option), "manually" peeking $9FB3 reads back as the value 1 (which I believe is associated with the "-echo raw" option). By "manually" I mean by typing in the POKE and PEEK commands versus running them in a program.

**Comment by mobluse** [comment]
I tried this program in both `x16emu` and `x64` (C64 emulator part of VICE) and it works in the same way on the screen:
```
10 LIST
15 PRINT "HELLO"
20 LIST
30 LIST
```
It only LISTs once on the screen and then terminates. I.e. HELLO is not printed. This seems to be how LIST in BASIC V2 is supposed to work.

When you use `-echo raw` the emulator echoes exactly what the ROM prints, and on C64 and x16emu a single CR (i.e. \x0D) is used as newline. It was the same on Apple II and macOS 9 and earlier. If you want newlines translated to LF (\x0A) you should use -echo or -echo iso.

You could try `x16emu -echo raw | xxd` in Linux to see exactly what is printed. Now you see it sometimes prints  '\x0A' but I think this is a bug (i.e. I don't think this was in the original C64 ROM). I think someone tried to adapt the ROM to Unix/Linux or Windows terminal. I reported this as an issue in the ROM https://github.com/commanderx16/x16-rom/issues/37.

There could still be some issue, as you say, when changing echo mode during runtime. Maybe it can only switch echo on or off during runtime, but not change mode. One has to study the emulator code.

**Comment by marksassistants0** [comment]
- Help with stored files? I don’t know what this is......any suggestion 
   - {"app_name":"SafariViewService","timestamp":"2019-10-08 11:17:59.45 -0400","app_version":"1.0","slice_uuid":"2eb38ae7-eb4a-3f8a-961b-e1610acc1cd4","adam_id":0,"build_version":"1.0","bundleID":"com.apple.SafariViewService","share_with_app_devs":false,"is_first_party":true,"bug_type":"109","os_version":"iPhone OS 13.1.2 (17A860)","incident_id":"69197C4C-0041-4079-AC7E-7C09514A9B91","name":"SafariViewService"}Incident Identifier: 69197C4C-0041-4079-AC7E-7C09514A9B91CrashReporter Key: f1e64151c8c7857ab61e3b6f2c52f52b416e7e67Hardware Model: iPhone10,4Process: SafariViewService [1130]Path: /Applications/SafariViewService.app/SafariViewServiceIdentifier: com.apple.SafariViewServiceVersion: 1.0 (1.0)Code Type: ARM-64 (Native)Role: unknownParent Process: launchd [1]Coalition: com.apple.SafariViewService [704]Date/Time: 2019-10-08 11:17:59.2086 -0400Launch Time: 2019-10-08 10:01:40.3583 -0400OS Version: iPhone OS 13.1.2 (17A860)Release Type: UserBaseband Version: 3.01.01Report Version: 104Exception Type: EXC_CRASH (SIGKILL)Exception Codes: 0x0000000000000000, 0x0000000000000000Exception Note: EXC_CORPSE_NOTIFYTermination Reason: Namespace RUNNINGBOARD, Code 0xdead10ccTriggered by Thread: 0Thread 0 name: Dispatch queue: com.apple.main-threadThread 0 Crashed:0 libsystem_kernel.dylib  0x0000000195d835f4 0x195d80000 + 138121 libsystem_kernel.dylib  0x0000000195d82a60 0x195d80000 + 108482 CoreFoundation  0x0000000195f2a068 0x195e81000 + 6923283 CoreFoundation  0x0000000195f25188 0x195e81000 + 6721364 CoreFoundation  0x0000000195f248bc 0x195e81000 + 6698845 GraphicsServices  0x000000019fd90328 0x19fd8d000 + 130966 UIKitCore  0x0000000199fba6d4 0x1995ca000 + 104219727 SafariViewService  0x0000000104c02428 0x104c00000 + 92568 libdyld.dylib  0x0000000195daf460 0x195dae000 + 5216Thread 1 name: com.apple.uikit.eventfetch-threadThread 1:0 libsystem_kernel.dylib  0x0000000195d835f4 0x195d80000 + 138121 libsystem_kernel.dylib  0x0000000195d82a60 0x195d80000 + 108482 CoreFoundation  0x0000000195f2a068 0x195e81000 + 6923283 CoreFoundation  0x0000000195f25188 0x195e81000 + 6721364 CoreFoundation  0x0000000195f248bc 0x195e81000 + 6698845 Foundation  0x0000000196264994 0x19625d000 + 311246 Foundation  0x0000000196264874 0x19625d000 + 308367 UIKitCore  0x000000019a05249c 0x1995ca000 + 110439968 Foundation  0x00000001963950b0 0x19625d000 + 12781289 libsystem_pthread.dylib  0x0000000195cc91ec 0x195cbe000 + 4554810 libsystem_pthread.dylib  0x0000000195cccaec 0x195cbe000 + 60140Thread 2 name: JavaScriptCore bmalloc scavengerThread 2:0 libsystem_kernel.dylib  0x0000000195da4c8c 0x195d80000 + 1506681 libsystem_pthread.dylib  0x0000000195cc64e0 0x195cbe000 + 340162 libc++.1.dylib  0x0000000195df67a8 0x195de8000 + 593043 JavaScriptCore  0x00000001a4b823fc 0x1a4afa000 + 558076
   - 
Sent from Yahoo Mail for iPhone


On Monday, October 28, 2019, 4:01 PM, Michael Steil <notifications@github.com> wrote:


Closed #174 via #191.
