### ISSUE TITLE
SDcard image problems. Emulator device 1 intercepts. Mounting directory as SDcard.

### ISSUE THREAD

**Issue by kghultland** [commanderx16/x16-emulator#176]
How does one create a small SDcard image using windows? The smallest sdcard that I have is 64 GB and the smallest I find in stores is 16GB. The only utilities I have found on PC create an image of the full SDcard and having a 64 GB .img file feels like overkill just to get 100 kilobytes of files accessible to assembly language in the emulator.

The emulator only intercepts the LOAD and the SAVE Kernal calls to device 1 and the assembly code I am porting from C64 to CX16 uses OPEN and reads and writes files line by line one character at the time. I could perhaps rewrite the code to SAVE the changed data using the SAVE call, but the LOAD is impractical when the files I need to read and parse are larger than the available normal memory and too large to fit in one piece in High RAM.

I know that this will not be an issue once we have a physical CX16 but in the meantime, it would be handy if the emulator supported all disk Kernal operations on the intercepted device 1.

Another possible solution would be if I could "mount" a directory on my PC as an SDcard directly and write/read files there from the emulator.

**Comment by mist64** [comment]
I'll include a blank image in emulator release r34. :)
