### ISSUE TITLE
BBR & BBS opcodes missing

### ISSUE THREAD

**Issue by Oleg-Imanilov** [commanderx16/x16-emulator#177]
I can't see opcodes in cpu/65c02.opcodes
Is there any reason why it is not there? More important now $ff - is "dbg" which in conflict with bbs7!

```
; **************************************
;              branch on bit
; **************************************
bbr0 zp 2 $0f
bbr1 zp 2 $1f
bbr2 zp 2 $2f
bbr3 zp 2 $3f
bbr4 zp 2 $4f
bbr5 zp 2 $5f
bbr6 zp 2 $6f
bbr7 zp 2 $7f

bbs0 zp 2 $8f
bbs1 zp 2 $9f
bbs2 zp 2 $af
bbs3 zp 2 $bf
bbs4 zp 2 $cf
bbs5 zp 2 $df
bbs6 zp 2 $ef
bbs7 zp 2 $ff
```

**Comment by Kobrasadetin** [comment]
This needs attention, as some (higher level languge) compilers could output correct 65c02 opcodes that will not work in the emulator.

**Comment by Pigu-A** [comment]
Those instructions (along with RMBx and SMBx) were added later in R65C02 which is ported back later in W65C02 (notice the prefix letters). However, they are not supported in 65C816 since it was extended from the initial 65C02 and should not be emulated since there is a plan to upgrade to that CPU.

**Comment by mist64** [comment]
I wouldn't say there is a *plan* for the 65816, but I think we should stick with the basic set of 65C02 instructions anyway – for now. 

We could implement them in the emulator, but we should put a conditional around the support.

**Comment by ekmett** [comment]
Related: #246

**Comment by mist64** [comment]
Fixed in https://github.com/commanderx16/x16-emulator/pull/287
