### ISSUE TITLE
Missing control over TILEW and TILEH in text modes

### ISSUE THREAD

**Issue by Serentty** [commanderx16/x16-emulator#179]
The [official specifications list](https://www.facebook.com/groups/CommanderX16/permalink/402529400498160/) for the Commander X16 mentions that “the 1 bpp tile modes in combination with 8x16 tile size will also allow for a standard VGA font to be used.” By “1 bpp tile modes” I'm assuming that it's referring to modes zero and one, the text modes. However, currently the emulator ignores TILEW and TILEH in these two modes, as can be seen in the code below.

```c
if (props->tile_mode) {
    props->tilew = 1 << (((reg_layer[layer][1] >> 4) & 1) + 3);
    props->tileh = 1 << (((reg_layer[layer][1] >> 5) & 1) + 3);
} else {
    props->tilew = 8;
    props->tileh = 8;
}
```

I discovered this when I went to use this feature in order to display Japanese text at a reasonable size and resolution, yet nothing happened.

**Comment by mist64** [comment]
I don't see this claim in the specification (Facebook is ^*&$^#%&!), and it's not in the VERA spec:

https://github.com/commanderx16/x16-docs/blob/master/VERA%20Programmer's%20Reference.md

@fvdhoef Can you comment?

**Comment by fvdhoef** [comment]
It is correct that tile mode 0 and 1 also support all combinations of tile width and height 8x8, 8x16, 16x8, 16x16. If the emulator doesn't emulate this now, that is an error.

**Comment by mist64** [comment]
A pull request would be gladly accepted. :)

**Comment by Serentty** [comment]
Alright, if this is supposed to be emulated, I'll take a look and see if I can figure out how to implement it.

**Comment by Kroc** [comment]
Can't access Facebook _at all_; can anybody perhaps mirror that doc please?

**Comment by indigodarkwolf** [comment]
Hopefully the fix is straightforward, just remove the if() and use the tile size logic from tiles modes for text as well:

```C
props->tilew = 1 << (((reg_layer[layer][1] >> 4) & 1) + 3);
props->tileh = 1 << (((reg_layer[layer][1] >> 5) & 1) + 3);
```

But even if it's harder than that, I expect the worst case would be looking at wherever checks `props->tile_mode` and `props->text_mode`, which shouldn't be too bad.

**Comment by Serentty** [comment]
I created a [branch](https://github.com/Serentty/x16-emulator/tree/resizable-text) where I removed the check on tile size. First tests seem promising. Understandably the text on the screen is all corrupted when switching the tile size, so I'll have to check more carefully to ensure that it's behaving properly.

**Comment by Serentty** [comment]
It seems that when the checks are removed, it does indeed work properly, as per my understanding of how it is supposed to work. For example, when characters are set to be double height, it continues on to load 100% more font data, which is easy to see from how whenever a letter is typed, you see two consecutive letters from the character set.

![image](https://user-images.githubusercontent.com/614548/66954462-71ce0600-f02e-11e9-96b7-493d90aa33f9.png)

I'll go and open a pull request for these changes.

**Comment by Serentty** [comment]
Done.

https://github.com/commanderx16/x16-emulator/pull/184

**Comment by Serentty** [comment]
I'm closing this because my pull request has been merged.
