### ISSUE TITLE
Vera interrupts not behaving properly

### ISSUE THREAD

**Issue by phelloe** [commanderx16/x16-emulator#187]
Might be a misconception on my part, but so far I have noticed the following behavior with the Vera IEN/ISR:
```asm
vera_ien = $9f26
vera_isr = $9f27
```

```asm
lda #0
sta vera_ien
```

will disable keyboard input and cursor blinking,

```asm
lda #1
sta vera_ien
```

will not result in vera_isr indicating that an interrupt has occured,

```asm
lda #2
sta vera_ien
```

will lock up the system and also not indicate that an interrupt has occured.

**Comment by indigodarkwolf** [comment]
Unless you're clobbering `$0314` and `$0315` with your own interrupt handler, then what's going on is the kernal is processing the Vera's VSYNC interrupt for you and clearing the Vera's interrupt bit on exit. The kernal uses VSYNC to process keyboard input, update the display, and "do other kernal-ish" things.

If you want to catch the Vera's VSYNC interrupt, overwrite `$0314` and `$0315` with a pointer to your own interrupt handler. Just make sure you either preserve the pointer to the original interrupt handler and jump back into it, or pull the appropriate registers off the stack before hitting `rti`. There's a little more info [on the wiki](https://github.com/commanderx16/x16-emulator/wiki/(ASM-programming)-Interrupts-and-interrupt-handling).

**Comment by phelloe** [comment]
That explains a lot. Apparently forgot to check the wiki on that matter. Thanks!
