### ISSUE TITLE
Write to file

### ISSUE THREAD

**Issue by lenniedv** [commanderx16/x16-emulator#194]
I have the following cc65 program to write a plain text file.
When I run this in the X16 emu release 33 i don't see the file on my local file system ?

#include <stdio.h>

#define LEN 256
int main ()
{
FILE * fp;
int i;
/* open the file for writing*/
fp = fopen ("1.txt","w");

/* write 10 lines of text into the file stream*/
for(i = 0; i < 10;i++){
fprintf (fp, "This is line %d\n",i + 1);
}

/* close the file*/ 
fclose (fp);
return 0;
}

**Comment by jackokring** [comment]
open 3,1,3,"GFX.BMP" gives an illegal device number, and so it appears that device 1 has no intercept for the local filesystem.

**Comment by mist64** [comment]
Known issue. OPEN/PRINT#/GET#/INPUT#/CLOSE does not work on device 1 in the emulator. Only LOAD/VLOAD/SAVE are supported.

**Comment by bobbyjim** [comment]
I've thought about what it might take to patch the KERNAL routines that are used by OPEN, INPUT#, GET$, PRINT#, and CLOSE.  Long version is here https://murray2.com/threads/host-filesystem-access.332/#post-2924

**Comment by mist64** [comment]
Fixed by e84dc1b24044c0daea7eb45f044a14bf68612fc9
