### ISSUE TITLE
r34 Graphic Mode Incompatibility Issue (640x480x256)

### ISSUE THREAD

**Issue by c64skate** [commanderx16/x16-emulator#196]
This example loads 5 seperate binaries to fill 125k of 128k VRAM to show 640x200x256 color picture. This works as expected in r33 but fails with garbage visuals in r34.

You can compile the source code using KickAssembler.

[640x200.zip](https://github.com/commanderx16/x16-emulator/files/3801542/640x200.zip)

**Comment by c64skate** [comment]
I made further investigation. I compared Composer and Layer0 registers between r33 and r34, they are identical. I've suspected some default value changes between two versions. Maybe i wasn't setting some register but it was working by the default value in the previous version but it seems like that's not it.

**Comment by c64skate** [comment]
i solved the issue. layer 1 now comes ON by default covering layer 0.

	// layer 1 configuration
	lda #$30
	sta $9f21
	lda #$00
	sta $9f20
	lda #$00
	sta $9f23

this solves the issue.

You have some default value problems. I have 3 of them noted down.

1) layer 1 should be off by default.
2) TILEW should come in 640 width mode instead of 320 since machine boots in 640 resolution.
3) Mouse comes ON even if there are no sprites. When you enable the first sprite, it follows the mouse. MOUSE 0 disables it from basic. But since mouse is not visible by default, sprite #0 shouldn't follow the mouse by default.

Makes sense, right?

**Comment by indigodarkwolf** [comment]
Well, I definitely agree that if the mouse is not visible by default, then the kernal should not force sprite 0 to follow the mouse by default, unless or until someone enables the mouse.

Would a workaround for r34 be to manually disable the mouse in our assembly programs with the kernal MOUSE function?

```asm
lda #0
jsr $$FF09
```

**Comment by c64skate** [comment]
> Well, I definitely agree that if the mouse is not visible by default, then the kernal should not force sprite 0 to follow the mouse by default, unless or until someone enables the mouse.
> 
> Would a workaround for r34 be to manually disable the mouse in our assembly programs with the kernal MOUSE function?
> 
> ```assembly
> lda #0
> jsr $FF09
> ```

Mouse is off-topic and i started this i know, but also i have to mention that disabling mouse with that kernal call stops the first sprite following the mouse but doesn't stop ps/2 port scanning which keeps stealing cycles and messing up IRQ timings when the mouse moved.

See here: https://github.com/commanderx16/x16-emulator/issues/197

**Comment by c64skate** [comment]
Btw, you we can close this ticket. There is nothing to fix. This is caused by default layer usage change at start up.
