### ISSUE TITLE
Mouse causes IRQ timing issues even if it is disabled

### ISSUE THREAD

**Issue by c64skate** [commanderx16/x16-emulator#197]
it is hard to prepare a simplified project for this at the moment, but you can see the problem from the demo project here.

https://github.com/c64skate/commander_x16_samples/tree/master/waterdemo

You can directly try waterdemo.prg (other assets are needed, it uses external files). You will see the flickering when mouse moves over the emulator screen. My code starts with;

	// disable mouse
	lda #$00
	jsr $ff09

So, even if you disable the mouse, mouse handling still a factor and affects timings.

Please let mouse features come disabled by default and be sure they don't cause any timing issues. Why should a keyboard / joystick only game or a demo suffer from this, right?

**Comment by mist64** [comment]
Agreed. When the mouse is disabled, PS/2 port scanning should be disabled.

**Comment by greg-king5** [comment]
> Agreed. When the mouse is disabled, PS/2 port scanning should be disabled.

Currently, the mouse cannot be disabled!

Hiding the mouse cursor must not actually disable the mouse itself.
Programs expect the mouse co-ordinates to stay "current" even when they hide the default pointer.  Therefore, we need another setting -- it would enable/disable the mouse interrupt handler.

And, of course, a reset would disable the handler, and hide the default mouse sprite.

**Comment by c64skate** [comment]
> Programs expect the mouse co-ordinates to stay "current" even when they hide the default pointer. Therefore, we need another setting -- it would enable/disable the mouse interrupt handler.

But one thing should not be missed here. Even if there were two seperate statuses for visibility and interrupt, both visibility and interrupt should be disabled by default unless someone needs them and set them to enabed state.

Currently, one major problem is mouse pointer seems to be hidden but it's not. It's not visible just because first sprite is not visible. But as soon as we enable the first sprite we see it's moving with the mouse. So this is a "corrupt" boot state. Either mouse sprite should be visible by default or first sprite shouldn't move with the mouse when it's enabled without setting any mouse flags.

So we have two seperate issues here.

1) corrupt mouse visibility state on boot
2) not being able to disable mouse interrupt handler

**Comment by mist64** [comment]
fixed by 4522ac205d8b54e8aba2eb756abebd7f46876ccb
