### ISSUE TITLE
Emulator continues to print "buffer full, skipping..." when mouse is off

### ISSUE THREAD

**Issue by MCPEmaniac** [commanderx16/x16-emulator#203]
The emulator continues to print "buffer full, skipping..." error messages to terminal in echo mode even when the mouse is turned off.

**Comment by c64skate** [comment]
"buffer full, skipping..." is another story but about disabling the mouse, it's covered in this ticket.

https://github.com/commanderx16/x16-emulator/issues/197

**Comment by mist64** [comment]
Fixed in ea1c7e0
