### ISSUE TITLE
Porting PetDraw to the X16emu

### ISSUE THREAD

**Issue by bobbyjim** [commanderx16/x16-emulator#208]
I'd like to try this, but tell me if this is the right direction.

Emulator work to expand filesystem access.
1. Intercept KERNAL calls to OPEN, CLOSE, CHRIN, GETIN, CHROUT, CLRCHN, and CLALL.
2. Fetch and use the data set by SETLFS and SETNM, CHKIN and CHKOUT... wherever those are.
(I know it's possible to use the monitor to load and save, but I'd really like SEQ file access in BASIC, so...)

Porting work.
1. Adjust screen RAM location.
2. Adjust color RAM location.
3. Adjust logic for changing text/background/border color (I know the X16 is ... different).

Thoughts?  Too ambitious?  Maybe I should just focus on getting I/O working for the local filesystem?

**Comment by FreeFull** [comment]
See https://github.com/commanderx16/x16-demo/tree/master/petdrawx16

**Comment by bobbyjim** [comment]
> See https://github.com/commanderx16/x16-demo/tree/master/petdrawx16

LOL!  Thanks for that.
