### ISSUE TITLE
binary dist missing CSS file in docs/ folder

### ISSUE THREAD

**Issue by tseemann** [commanderx16/x16-emulator#213]
I unzipped the macos binary dist and I looked at the HTML docs inthe `docs` folder, but  there is no `github-pandoc.css` file so the tables don't render nicely.

```
KERNAL-BASIC.html:  <link rel="stylesheet" href="github-pandoc.css" />
Programmer's Reference Guide.html:  <link rel="stylesheet" href="github-pandoc.css" />
README.html:  <link rel="stylesheet" href="github-pandoc.css" />
VERA Programmer's Reference.html:  <link rel="stylesheet" href="github-pandoc.css" />
```

**Comment by greg-king5** [comment]
> I unzipped the macos binary dist.; and, I looked at the HTML docs. in the `docs` folder; but, there is no `github-pandoc.css` file; so, the tables don't render nicely.

Only release 30 seems to have it.

**Comment by tseemann** [comment]
Thanks @mist64
