### ISSUE TITLE
Not able to build web assembly with emscripten 1.39.3

### ISSUE THREAD

**Issue by gaekwad** [commanderx16/x16-emulator#215]
I get the following linking-time error when I try to do a web assembly build with the latest emscripten:

```
wasm-ld: error: duplicate symbol: status
>>> defined in cpu/fake6502.o
>>> defined in extern/src/ym2151.o
```

**Comment by sebastianvog** [comment]
I can't seem to reproduce this  usign 1.39.3 . Can you give some more information about your environment?
can you do a emcc -v and post the output

**Comment by gaekwad** [comment]
Are you sure you're building with the YM2151 enabled?

```
make wasm WITH_YM2151=1
```

I'm currently on MSYS.

```
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.3
clang version 10.0.0 (Cswircachegitchromium.googlesource.com-external-github.com-llvm-llvm--project cb47b8783017a76c5f2e4b974cfd6b22c9f1d5ff)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: c:/emsdk/upstream/bin
shared:INFO: (Emscripten: Running sanity checks)
```

**Comment by sebastianvog** [comment]
Aaah i see, i got confused with my environments. It looks like emscripten changed the default compiler backend in the latest version. The default changed from fastcomp to llvm, and I see the error now when compiling using the default 'latest' SDK. As a workaround you could activate the fastcomp with 'emsdk activate latest-fastcomp'. But i will push up a fix.
