### ISSUE TITLE
Autorun from shadow RAM doesn't work again.

### ISSUE THREAD

**Issue by paulscottrobson** [commanderx16/x16-emulator#220]
Loading a .PRG file to run at $A000 displays a half vertical block in place of the first S and crashes.
	* = $A000
h1:	jmp 	h1
Built with  64tass -c test.asm -o test.prg
Run with x16emu -debug -prg test.prg -run
This does a stack crash ; the other one is a consequence of what I'm working on.

**Comment by mist64** [comment]
Does not reproduce. Probably fixed by e84dc1b.
