### ISSUE TITLE
r35 - Linux - While in basic issues with banked ram use

### ISSUE THREAD

**Issue by Usoilworker** [commanderx16/x16-emulator#226]
In immediate mode ram bank 0 always active Pokes to $9f61 not persistent.

From within a basic program bank selected bank will stay active for a few cycles then it switches to bank 0.

**Comment by mist64** [comment]
This should already be fixed in the repo. Can you build a new ROM and check?

**Comment by Usoilworker** [comment]
Unfortunately I have not figured out how to  'make' cc65 on my chromebook linux beta to be able to compile my own roms yet.  I will give it another go over this break or use the desktop debian to compile it thanks for the heads up on the repo

**Comment by mist64** [comment]
For the meantime:
[rom.bin.zip](https://github.com/commanderx16/x16-emulator/files/4003678/rom.bin.zip)

**Comment by Usoilworker** [comment]
Thank you !!!!

**Comment by Usoilworker** [comment]
I've not filed an issue before nor closed one out The updated rom.bin fixed the issue thank you again for the quick response.
