### ISSUE TITLE
Corrupted BASIC program using -prg or -run

### ISSUE THREAD

**Issue by rsbohn** [commanderx16/x16-emulator#23]
When I start the emulator with -prg I can list the program, but after I run it the first line is corrupted.

Running pre-R29 master branch, OS X.

**V:**

    10 FOR X = 1 TO 20
    20 PRINT TI
    30 NEXT

**Transcript:**

58252:cleanroom rsbohn$ ./x16emu -prg V -echo
???  ߒ   ?  ??
? ?  ߒ ?  ??  **** COMMANDER X16 BASIC V2 ****
?  ?  ?   ??
     ?  ?     2048K RAM SYSTEM
?  ?  ?   ?
? ?  ?? ?  ߒ  38655 BASIC BYTES FREE
?  ??   ?  ?

READY.

**LIST**
10 FOR X = 1 TO 20
20 PRINT TI
30 NEXT

READY.

**RUN**
?SYNTAX  ERROR IN 10

READY.

**LIST**
88 
20 PRINT TI
30 NEXT

READY.

**Comment by rsbohn** [comment]
btw it would be helpful to put build versions on both the kernal and the BASIC interpreter.

**Comment by rsbohn** [comment]
Same result with r29 rom.bin.

added QmPEGsgybxmjXCFRnpdYfcLnSELRT2uCubS27v5Lf2tRQn mac29/KERNAL-BASIC.html
added QmWqjgbbatcF7zcJVLeQXVJXz2gwEW5MNMRkD1Ev4v3BXU mac29/Programmer's Reference Guide.html
added QmU4L9SamVirBLZ2GonC9ZUV9kCm654ULQGgMH3FYiLnfb mac29/README.html
added Qmc73T5oK73mYLqcjxxqQEFoESHuF5mVFzhwHrUXuKc9qW mac29/chargen.bin
added QmaeHDbnUa6HuGWLWXX2UE4hGSsBN4WAANttHik8e7dFXT mac29/rom.bin
added QmTXEvuMAWp9NmGQ3oxUZXKQ58Wscv7A3Ci9PerKu5oJ1S mac29/vera-module v0.7.pdf
added QmRiGCipSWVUMAcFYxMXGB5Lvjqmyx9msdCwWdXFWVGoqi mac29/x16emu
added QmaEwn5ix5SNzNCisT7FZAZJ1gMVJKxhGerQPryQWXmmc9 mac29

**Comment by mist64** [comment]
Yes, it's a problem with the emulator. It injects the program, but does not set the "end of BASIC program" pointer, so when creating a variable, it overwrites the program.

Working on it.
