### ISSUE TITLE
r36 / BASIC: long identifiers return syntax error

### ISSUE THREAD

**Issue by bobbyjim** [commanderx16/x16-emulator#234]
On Commodore machines and emulators, your code is free to call variables with long labels, e.g.

CARGO$ = "400"

What happens is that CA$ gets the value "400"; in essence, the interpreter happily ignores the extra characters.

In the r36 X16 emu, we instead get a syntax error:

CARGO$ = "400"

?SYNTAX  ERROR
READY.

**Comment by EgonOlsen71** [comment]
It's not about the length, it's about the GO in the name. GO is a keyword in BASIC (from GOTO). You can't use it in a variable name, not here and not on the C64 either. CARGO$="400" will give you a syntax error on the C64 as well.

**Comment by bobbyjim** [comment]
Oy!  Thank you.

**Comment by greg-king5** [comment]
> `GO` is a keyword in BASIC (from `GOTO`).

`GOTO` is one token.  `GO` is a different token; it can be used with the `TO` token (from `FOR` statements).  `GO TO` is interpreted as meaning `GOTO`.

Also, BASIC 7 on the C128 supports `GO 64` to go from 128 mode to 64 mode.

**Comment by EgonOlsen71** [comment]
> `GOTO` is one token. `GO` is a different token; it can be used with the `TO` token (from `FOR` statements). `GO TO` is interpreted as meaning `GOTO`.

I know, that's why I talked about keywords and not tokens. The tokenization is just an implementation detail that doesn't matter for the explanation why CARGO isn't valid.
