### ISSUE TITLE
cc65 issues with r36

### ISSUE THREAD

**Issue by steph72** [commanderx16/x16-emulator#235]
I don't know whether it's the fault of the emulator or the cc65 runtime library (cc65 version 2.18), but there are  problems with cc65 since r36 of the emulator. 

My 8-bit-multiplatform-yahtzee-clone "kkniffel" (https://github.com/steph72/kkniffel) runs fine with r35 of the emulator. With r36, multiple things seem to be broken:

- bgcolor() doesn't work
- cputs() breaks lines at the wrong position
- cgetc() hangs the machine

(tested with linux and mac versions of the the r36 emulator)

**Comment by greg-king5** [comment]
Yep, cc65's cx16 library hasn't been upgraded to r36, yet.

**Comment by steph72** [comment]
fixed with the new version of cc65, thank you very much!
