### ISSUE TITLE
EMSCRIPTEN version online doesn't exist for r36 "Berlin"

### ISSUE THREAD

**Issue by mobluse** [commanderx16/x16-emulator#240]
There is no EMSCRIPTEN version online for r36 "Berlin", since TEST1 command etc. doesn't work in the online versions. 
https://x16.tmp2k.com/
https://sebastianvog.github.io/x16-emulator/x16emu.html

**Comment by sebastianvog** [comment]
Updated https://sebastianvog.github.io/x16-emulator/x16emu.html

**Comment by Tmp2k** [comment]
@sebastianvog I've just tried "make wasm" for r36 but I'm getting the following error:
`machine type must be wasm32`

It looks like the target is set wrong, I've had a look through the make file but I'm not really familiar with make.  Any ideas?

**Comment by Tmp2k** [comment]
@mobluse I've now updated https://x16.tmp2k.com/ to r36.

I didn't get it to compile, I just borrowed the compiled assets from @sebastianvog website lol

**Comment by sebastianvog** [comment]
@Tmp2k  I don't know why you are getting the machine type must be wasm32 error.
Perhaps a make clean, and possibly updating your emscripten sdk ? 
`emsdk update` `emsdk install latest`

Audio does work (although it has a performance hit especially on older machines) with `make wasm WITH_YM2151=1`
