### ISSUE TITLE
Flush after writing a character to UART out file

### ISSUE THREAD

**Issue by juju2143** [commanderx16/x16-emulator#244]
https://github.com/commanderx16/x16-emulator/blob/cf98ca4000177b924d4bb24fcf1654029803b942/vera_uart.c#L106

You might want to add a `fflush` after the `fputc` so characters immediately gets written to the file when you use `-uart-out`. It's quite useful with named pipes (mkfifo on Linux).

**Comment by juju2143** [comment]
I fixed it on Linux, I basically set the fopen non-blocking and check if there's data available or not

I don't know how it works in Windows but it works for me

See juju2143/x16-emulator@f95d976 (also includes something for JavaScript, I don't know if you want that :smiley:)

**Comment by mist64** [comment]
The VERA UART has been removed. :(
