### ISSUE TITLE
Missing 65c02's WAI instruction

### ISSUE THREAD

**Issue by ekmett** [commanderx16/x16-emulator#246]
The WAI instruction for the 65c02 can be used for more prompt IRQ response.

It places the CPU in low power mode waiting until an IRQ happens, at which point it immediately wakes up, saving a couple clock cycles. This replaces a the usual spin loop pattern.

More interestingly, if the interrupts are disabled, when the CPU is frozen waiting on a WAI, the IRQ just resumes at the next instruction instead of executing the interrupt handler. This saves all the setup of firing off the IRQ handler, RTI to come back, etc. This can be handy if you wanted to do something tricky and time sensitive with, say, the VERA's IRQ for reaching a given line.

**Comment by mist64** [comment]
Fixed in https://github.com/commanderx16/x16-emulator/pull/287
