### ISSUE TITLE
On Windows -prg and -run loads are still truncated. LOAD"PROGRAM" is working now.

### ISSUE THREAD

**Issue by a42o** [commanderx16/x16-emulator#25]
This is working fine now using the LOAD and SAVE command from the emulator prompt. Just not from -prg and -run.

**Comment by mist64** [comment]
Can you provide a demo .PRG that reproduces this?

**Comment by a42o** [comment]
![x16_Capture](https://user-images.githubusercontent.com/54961330/64479996-b0e67d00-d18d-11e9-9c4d-38e64c64ed80.JPG)
[STREAM.zip](https://github.com/commanderx16/x16-emulator/files/3587008/STREAM.zip)

Here's a screen shot and the PRG file. The prg file worked fine when I typed it in and saved it from the emulator. I am running r29.

**Comment by a42o** [comment]
All is good if I download this PRG from the X16 FB page and load it using LOAD"STREAM.PRG". If I try  -run or -prg it adds extraneous lines and errors out.

**Comment by mist64** [comment]
This reproduces on Mac as well.

**Comment by mist64** [comment]
This is fixed in a8af94b0b3eb3680b6e16b33f6a3a2725d34c88d. Will be released in r30.
