### ISSUE TITLE
r37 registers duplicated / missing

### ISSUE THREAD

**Issue by playboxmegaboy** [commanderx16/x16-emulator#263]
$9f29-$9f2c have been duplicated according to the docs.

DC_HSTART, DC_HSTOP, DC_VSTART, DC_VSTOP are missing.

**Comment by StinkerB06** [comment]
The duplication in the docs is intentional. You just have to switch between them via `DCSEL` in $9F25.

**Comment by indigodarkwolf** [comment]
Suggest closing this issue, as it's not an issue.

**Comment by playboxmegaboy** [comment]
Thanks
