### ISSUE TITLE
R37 Basic - Ctrl+C does not interrupt when waiting for input

### ISSUE THREAD

**Issue by fabbrimichele** [commanderx16/x16-emulator#268]
When a basic program waits for the input, Ctrl+C does not interrupt the program execution.

**Comment by greg-king5** [comment]
That is traditional behavior.  It was inherited from Commodore BASIC.  The `STOP` key doesn't cancel statements; it cancels programs when the interpreter is in-between statements.

You must tap the `Enter` key, then quickly hold down the `Esc` key (or `Ctrl-C`).  If you didn't do it fast enough (before BASIC did another `INPUT`), then you must keep alternating between `Enter` and `Esc` -- quickly -- until the program stops.

**Comment by fabbrimichele** [comment]
Ah I didn't know it.
Thanks for the explanation!
