### ISSUE TITLE
Need for display of zero page registers R0-R15 in debugger

### ISSUE THREAD

**Issue by mjallison42** [commanderx16/x16-emulator#278]
Registers R0-R15 used frequently by new kernal calls. It would be useful to display these in the debugger. 

A pull request is linked with this debugger feature implemented. 
(Since this is such a useful model, also displays extended 16 bit values "x16" - "x20").

#277

**Comment by JimmyDansbo** [comment]
As the pull-request is merged, maybe this issues could be closed?

**Comment by mjallison42** [comment]
PR merged, no need for the issue to remain open.
