### ISSUE TITLE
Update icon.c with new PETSCII version

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-emulator#280]
The emulator icon needs to be updated to reflect the new PETSCII version of the logo:

![new_logo](https://user-images.githubusercontent.com/869384/87012707-e3a43c00-c1c9-11ea-9c93-d5072768f9bb.png)

The data is in icon.c. There is also icon.xcf, which is just for reference and unused. I think it should be removed while at it.

**Comment by indigodarkwolf** [comment]
Is there a particular timeframe you'd like to have this done by? I don't want to use up a good first issue for anyone interested in contributing to the emulator, but I'm also eager to look into issues or improvements (and if there's an r38 "coming soon", obviously it would be nice to have the new icon to go with it).

**Comment by indigodarkwolf** [comment]
Well, I had time and the inclination, and most of the issues really seem like ROM/kernal issues rather than emulator ones. Maybe I'll go and add the missing BBR/BBS instructions to the 65c02 emulation next, having dipped my toe into WAI.
