### ISSUE TITLE
64x64 sprites wrap to the top of the screen before scrolling off the bottom of the screen.

### ISSUE THREAD

**Issue by indigodarkwolf** [commanderx16/x16-emulator#283]
If you run [the x16-spiral demo on the web emulator](https://www.commanderx16.com/emulator/x16emu.html?manifest=/emulator/37-x16-spiral/), you'll see that the box sprites can't spiral off the bottom of the screen, and instead get moved to the top of the screen. This appears to be because the emulator is enforcing a maximum sprite height of `0x200 - sprite_height`, or 448 for a 64-pixel tall sprite.

Question for @fvdhoef: Is this accurate to the behavior in the hardware? If not, what are the VERA's rules for wrapping sprite positions, so that we can fix the emulator?

**Comment by fvdhoef** [comment]
This isn't correct. On real hardware calculations are done on 10-bit coordinates. So a 64-pixel tall sprite will not only wrap to to top of the screen when the Y coordinate is larger than 1024-64.

**Comment by indigodarkwolf** [comment]
Great, thanks! I've submitted a pull request to fix the sprite wrapping.
