### ISSUE TITLE
Emulator hyper call SAVE() doesn't match behavior of LOAD() wrt to RAM banks.

### ISSUE THREAD

**Issue by mjallison42** [commanderx16/x16-emulator#292]
Emulator hyper call SAVE() doesn't match behavior of LOAD() wrt to RAM banks.

LOAD() correctly calculates RAM addresses for currently selected RAM bank, but SAVE does not. 
Attached PR copies address calculation from LOAD() into SAVE().

#291

**Comment by mist64** [comment]
e84dc1b changed the hypercall architecture so that the emulator reuses the ROM's logic and only deals with reading/writing bytes. This causes the emulator to behave the same with the host filesystem as it does with the SD card.
