### ISSUE TITLE
BRK in the monitor locks up

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-emulator#3]

**Comment by oziphantom** [comment]
at first it just seemed that the 0316 vector points to "no mans land", however even fixing this to point to FF00 the monitor entry point causes it to still lock up.. making it point to the address that FF00 points to in the RAM trampoline, also causes it to lock up. Although sometimes it did eventually exit, either with a strange error or stuck in a loop printing an error msg, once it printed the Commader 16 logo and nothing else...

**Comment by mist64** [comment]
Fixed in https://github.com/commanderx16/x16-rom/commit/af6f3647b093dbe6e915caf704685f2e2e6680bb
