### ISSUE TITLE
Laggy mouse movement

### ISSUE THREAD

**Issue by Elektron72** [commanderx16/x16-emulator#308]
On my computer (running Linux Mint), mouse movement is laggy in the emulator, and it takes a short amount of time for the pointer to catch up with its actual location. I believe this is because SDL2 sometimes sends up to 5 or 6 mouse events each frame. If the X16 is not supposed to handle more than one mouse update per frame, the pull request I am going to submit will prevent the emulator from sending more than one update each frame by combining the multiple updates from SDL2, which should fix this issue.

**Comment by lmihalkovic** [comment]
have you found the response to the core question of: what will the x16 behavior be? (will it indeed update only once per frame? ... now that have looked more closely at the mainboard, I saw that PS/2 is not located with VERA. I guess the response to that question is inside the ROM code in the v2 branch, right?!
