### ISSUE TITLE
YM2151 code should be compiled as a shared library to comply with GPL2+

### ISSUE THREAD

**Issue by daschewie** [commanderx16/x16-emulator#320]
The MAME project as a whole is made available under the terms of the GNU General Public License, version 2 or later (GPL-2.0+), since it contains code made available under multiple GPL-compatible licenses.

GPLv2.1 and earlier include what is known as the “GPL linking exception”. This essentially means that your software can include GPL'd code so long as it's compiled by itself and linked independent of the calling executable.

The would allow us to keep the project licensed as BSD while enabling YM2151 in the release binaries.

**Comment by Elektron72** [comment]
I cannot find any record of this exception except on specific projects. The license as a whole still applies to dynamically linked libraries. As far as I can see, the only way around this issue would be either to re-license the project under the GPL, or find a new YM2151 emulator.

**Comment by daschewie** [comment]
> I cannot find any record of this exception except on specific projects. The license as a whole still applies to dynamically linked libraries. As far as I can see, the only way around this issue would be either to re-license the project under the GPL, or find a new YM2151 emulator.

I think you are correct, I maybe confusing it with the LGPL.
