### ISSUE TITLE
Proposal: video driver

### ISSUE THREAD

**Issue by lmihalkovic** [commanderx16/x16-emulator#325]
Ever considered extracting the SDL related code out of video.c?  The idea is to create a video_driver layer with different implementations, the first one being SDL.

It would addess:
* #236 by allowing a video_driver_null which does zero display (can still create the window in the short term to avoid the having to gather all the SDL code from everywhere)
* some interesting experimental things which I will talk about when I am a bit further along ... but I do believe that this one is worth exploring

I did it locally and it all still works just fine

**Comment by kktos** [comment]
Another pretty good idea you have :)
I'm seeing immediately the ability to switch to opengl/Dx/vulkan, for instance....
Nice :)
And neat too.
I'm on.

**Comment by lmihalkovic** [comment]
so when I made this proposal, I didn't realize that I was going on the wrong path .. that first version works, but I realized I made the cut at the wrong location: the driver side was too big... yesterday I made #331 ... and this one is much better cut.. in a sense I now have 3 different pieces the general part, the SDL part (but there is still some SDL code inside the debugger for eg) and the vera part (no SDL at all)

**Comment by mist64** [comment]
Agreed, VERA video emulation should be independent of SDL. (How is this issue different from #331)

**Comment by lmihalkovic** [comment]
@mist64  this proposal was predicated on the wrong thoughts about where to split the code of video.c ... since then I saw what I had missed before. #331 is the better of the 2 ideas... and what I now have in my codebase. 

in short, this was starting from video.c and trying to extract the UI interaction (try to add an abstraction from main.c into video.c ) .. so change code from the viewpoint of main. ... but that was missing the bigger opportunity that your code offers: #331 starts from the other side and carve out of video.c what is essentially a working software VERA. I now have it as an independent library ... I am sure you mind can start to picture what that truly means .....
