### ISSUE TITLE
Add support for I2C and MCP7940N RTC

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-emulator#333]
The Proto #2 hardware has a MCP7940N RTC chip connected over I2C.

**Comment by kktos** [comment]
Some sources of info:
- a lib in C/CPP to look at for how to interact with the MCP
https://github.com/Zanduino/MCP7940
- a 6502 implementation of I2C
http://retro.hansotten.nl/6502-sbc/lee-davison-web-site/i2c-bus-interface/

**Comment by mist64** [comment]
I ended up using Dieter Hauer's implementation: 0c1374ab35543c89fe24ae073895bd457ec8f1a7

Adapted for X16, and RTC/SMC driver added here: 6fee27918bb7fb4ddd7569ca392f16077473f1a5
