### ISSUE TITLE
Fix for msys2 mingw64 compile warning treated as error

### ISSUE THREAD

**Issue by CasaDeRobison** [commanderx16/x16-emulator#344]
In main.c, at line 793 (as I write this) is a line:

    printf("%s %lu\n", nvram_path, sizeof(nvram));

Building it on Windows with msys2 mingw64, it complains that `sizeof(nvram)` is a long long value, not a long value.

Simple fix is to change the format specifier from %lu to %zu, available since C99. This will make the line safe for different sizeof types.

If you'd rather have this in a PR, I can do it, it just seemed far easier to post this here than to fork the repo / change / commit / PR / etc.

**Comment by mist64** [comment]
Sorry, this line was not supposed to be checked in. Fixed in 062fc94.
