### ISSUE TITLE
HEX$ problem on macOS in r38

### ISSUE THREAD

**Issue by javajini** [commanderx16/x16-emulator#346]
I'm running X16 r38 on macOS Big Sur 11.2.3. When I try to execute this code in direct mode I get:

        PRINT HEX$(218)
        ?BAD SUBSCRIPT  ERROR
        READY.

It is the same no matter what number I try to convert.

**Comment by mist64** [comment]
This feature is not in r38. The first release to include it will be r39, due to be out soon.

**Comment by javajini** [comment]
Thanks. I misread the docs. I appreciate all the work that you all are doing.
