### ISSUE TITLE
Addressing mode emulation bug?

### ISSUE THREAD

**Issue by rkurbatov** [commanderx16/x16-emulator#352]
I'm totally newbie in the world of Commodore so just started learning the assembly language of 6502 and addressing modes.

There are two indexed modes: zero page and absolute.

```
lda #$34
ldx $20
sta $F0,x
```

The resulting address is $F0 + $20 equals to $110 but it wraps around the page size ($FF) and result is $10. That's described in lot of tutorials and guides.

But what about absolute mode?

```
lda #$34
ldx $20
sta $FFF0,x
```

The resulting address here is $10010. Should it wrap around $FFFF and turn into $0010 or just point to nowhere so no data would be written?

The testing program I wrote and debugged does nothing - no memory value changes. Is it the correct behavior? Can somebody check on real hardware?

**Comment by MJoergen** [comment]
The line
```
ldx $20
```
should probably be
```
ldx #$20
```

To answer your question: absolute mode wraps around as you describe.

**Comment by rkurbatov** [comment]
Stupid me! Just came here to tell I was wrong because using ZP addressing in LDX instead of immediate one.

And yes, it wraps. Thank you @MJoergen and sorry :)

**Comment by rkurbatov** [comment]
Like I checked the source code and found this:
```
    ea += (uint16_t)x;
```

While `ea` is declared as `uint16_t` and should also "wrap" around `$FFFF`. So I realized the problem is in my code :)
