### ISSUE TITLE
"Keyboard NES" emulation bug

### ISSUE THREAD

**Issue by cyborgar** [commanderx16/x16-emulator#357]
This may be fixed in the next version, but the current emulator starts the NES keyboard emulation off at state 255 instead of 0 when programs are started with the -run option. This "repairs" itself after the first use of any of the keys and does not happen without using -run.

Can be reproduced with this small (TESTJOY.BAS) program

10 J=JOY(1)
20 PRINT CHR$(147);J
30 GOTO10

Just run with

x16em.exe -prg TESTJOY.BAS -run

**Comment by mist64** [comment]
255 means that no such joystick is attached. If you start your program with `-bas` and `-run`, you never touched the keyboard (the emulator injected the characters through different means), so the KERNAL can't know whether a keyboard is attached.

r39 has more explicit joystick numbers (0 = keyboard, 1+ = actual controllers), but the behavior is the same.
