### ISSUE TITLE
Web Based Emulator can't properly concatenate two strings when variable names begin with same 2 characters

### ISSUE THREAD

**Issue by efduggan** [commanderx16/x16-emulator#360]
Using the online emulator (r38) to test out a simple program. Two variables began with the same two characters and the variable names were distinct, yet the results printed looks like the computer got confused.

Try this code :
```
01 PRINT "CONCATENATION OF DIFFERENT NAMED VARIABLES WORK"
10 AC1$ = "ONE"
20 BC2$ = "TWO"
30 CC3$ = AC1$ + BC2$
40 PRINT "CC3 IS " CC3$
41 REM ONETWO APPEARS ONSCREEN - CORRECT

51 PRINT: PRINT "CONCATENATION OF SIMILAR NAMED VARIABLES FAILS"
60 DC1$ = "THREE"
70 DC2$ = "FOUR"
80 DC3$ = DC1$ + DC2$
90 PRINT "DC3 IS " DC3$
91 REM FOURFOUR APPEARS ONSCREEN - INCORRECT
```

Unknown if this occurs in the computer based emulations.

**Comment by lgblgblgb** [comment]
I'm not so familiar with the BASIC used in the X16 project (so I'm sorry if I am wrong here), but - at least - traditional Microsoft-BASIC derivatives (including Commodore BASICs) use the first two characters of the variable names only. Thus DC1$ and DC2$ and DC3$ is the same variable as only the "DC" part is important for the BASIC interpreter (first two characters of the variable name, again). This always worked this way on BASIC implementations having this ... well ... "feature" :)

**Comment by efduggan** [comment]
Yes, the X16 is limited to 2 character variable names in its BASIC. I verified it in the Vic-20 basic manual on page 87.
