### ISSUE TITLE
Emulator can't show any graphics

### ISSUE THREAD

**Issue by Arbars** [commanderx16/x16-emulator#363]
Source branch - Master
Source version - since last commit
SDL2 version - 2.0.14
Make version - 4.3

Result - emulator showing only blue background and nothing more (see attachement)

All posible libraries from SDL2 framework is installed.
ROM file used from release archive on the site.

![x16-emu-blue_screen](https://user-images.githubusercontent.com/10302498/128803649-17beb239-1c66-4c09-bdc5-648a7e11e235.png)

**Comment by Elektron72** [comment]
The latest release version of the ROM (r38) isn't compatible with the emulator's master branch. You'll need to build the ROM from its master branch.

**Comment by irmen** [comment]
I think this can be closed?
