### ISSUE TITLE
Build fails when -Wall is set

### ISSUE THREAD

**Issue by jestin** [commanderx16/x16-emulator#372]
This is a very minor issue, but I thought it should still be documented in case anybody searches for it when they can't build.

`make` fails on linux (Ubuntu) when `-Wall` is set in the makefile after commit ab15e58.  This is because the functions `triangle_blamp` and `calc_freq_3` are defined but not called, and `-Wall ` will treat this as an error.

The solution is either to remove `-Wall` from the `CFLAGS` in the makefile, or to comment out (or delete)  `triangle_blamp` and `calc_freq_3`.  If the latter route is taken, you will also need to comment out `poly_blamp`.  All three of these functions can be found in `src/vera_psg.c`.

**Comment by mist64** [comment]
Prepending `__unused` to these functions' signatures should work too.

**Comment by mist64** [comment]
@jestin Can you try whether this fixes it?

**Comment by jestin** [comment]
Sorry for not getting to this right away.  I had to wait until the weekend to have time.

On my Ubuntu system, `__unused` is not defined.  I've gotten it to work by replacing `__unused` with `__attribute__((unused))`.

From what I understand, this is a point of contention between the BSD lineage and that of glib:  https://bugzilla.kernel.org/show_bug.cgi?id=14186

Apparently Debian packages used to include the following as a fallback:

```
#ifndef __unused
# ifdef __GNUC__
#  define __unused __attribute__((unused))
# else
#  define __unused
# endif
#endif
```
This may cause conflicts as spelled out here, however:  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=522773

Unless I'm missing something I don't believe `__unused` to be an out-of-the-box option for at least Debian based systems like Ubuntu.  I haven't tried on others.
