### ISSUE TITLE
clock_set_date_time() and clock_get_date_time() not working anymore

### ISSUE THREAD

**Issue by irmen** [commanderx16/x16-emulator#384]
The new r39 kernal seems to have a problem with the RTC:

`clock_set_date_time()` -> no longer seems to do anything (except on box16, where it still works, odd?)
`clock_get_date_time()` -> no longer ticks, always returns the same date and time (all zeros)

I'm working on a smaller example program but attached is the demo program I've been using for this API.  It's supposed to display a ticking clock somewhere in 2022.  the counter is from the RDTIM() routine, which still works
[datetime.prg.zip](https://github.com/commanderx16/x16-rom/files/8402854/datetime.prg.zip)

**Comment by mist64** [comment]
@akumanatt This looks wrong:
```
return (~via[0].registers[2] & (ps2_port[1].out | i2c_port.data_out)) |
       (via[0].registers[2] & (ps2_port[1].in | i2c_port.data_in));
```

The i2c_port value must be `<< 2`, as it was in the previous version.
