### ISSUE TITLE
Ctrl+R and debugger hangs on WAI

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-emulator#392]
Minimal test case

```
POKE $8000,$CB
POKE $8001,$80
POKE $8002,$FD
SYS $8000
```

That's
```
WAI
BRA *-1
```

Thanks MooingLemur.

**Comment by indigodarkwolf** [comment]
Closing this, but there should be a new issue opened regarding the debugger behavior for WAI: When attempting to step during a WAI, the debugger only steps one cycle, instead of stepping until the WAI instruction ends.
