### ISSUE TITLE
R40 x16emu: error when using -prg option, first file on disk read instead of given filename

### ISSUE THREAD

**Issue by FlightControl-User** [commanderx16/x16-emulator#398]
Using the -prg option to start the x16emu R40 results in an incorrect behaviour.

It seems that now, when -prg is used, the emulator tries to load the first PRG from the disk, which is incorrect.
When you attach an SDCARD with multiple files attached, the -prg option will load the first PRG from that SDCARD.
Imagine you have multiple PRG files on that disk.

So, if possible, is it a lot of work to specify exactly the file name to be loaded so that the load process in the emulator will use the base file name given, instead of the ":*"?

kind regards,
Sven

**Comment by mist64** [comment]
This is what it should work like right now: When specifying `-prg` and `-sdcard`, the emulator still loads from the host filesystem. It will special case the first LOAD":*", direct it towards the host fs, and attach the SD card only afterwards. The ":*" looks like it's the first file from SD card, but it isn't.

Is this what you are seeing?

**Comment by FlightControl-User** [comment]
I'm sorry but not really. It seems to load an erroneous file.

**Comment by FlightControl-User** [comment]
![image](https://user-images.githubusercontent.com/13690775/166114686-eb56a781-fe1f-47da-9171-c70100a3cb8e.png)

**Comment by FlightControl-User** [comment]
I've also recorded a NEW video, that explains exactly the problem situation. Don't know what i was thinking this morning. I think it was the coffee...

https://screencast-o-matic.com/watch/c3fvDKVYCge

Sven

**Comment by mist64** [comment]
Reproduced.

**Comment by mist64** [comment]
Autoboot broke it. The host filesystem hack only works for the first file, and with autoboot support, the autoboot file is the first one.

**Comment by FlightControl-User** [comment]
Do you think you can do a fix for this?

**Comment by mist64** [comment]
The commit referenced above fixes it.
