### ISSUE TITLE
Support keyboard shortcuts on Windows and Linux

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-emulator#4]
The Cmd + R (reboot) and Cmd + S (save) shortcuts are currently only supported on macOS, because they rely on the Cmd key.

Instead of Cmd, on Windows and Linux, we should probably use the Ctrl key – even though Ctrl + R already means "reverse" and Ctrl + S means "home" in the EDITOR, since these functions can be reached through other keys/combinations as well.

**Comment by alextrevisan** [comment]
CTRL+WIN+R resets the emulator =)

**Comment by mist64** [comment]
Fixed in e1a7b3d364ac160001275da0765546ecc79b4e89
