### ISSUE TITLE
BASIC Memory Corruption

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-emulator#400]
[kelli217 says](https://www.commanderx16.com/forum/index.php?/topic/2769-emulator-r40-released/&do=findComment&comment=19210):

I've included the tokenized BASIC program. There's something odd about it.
If you load this, list it to make sure it's okay, then run it, then list it again, you should find new lines added to the program.
In fact, I've loaded the program, and just made some edits to it (like changing the color specified by D to something like D+127 or whatever) and not even run it, and listed it and gotten new lines added.
If I type it in manually, it works fine. Something about the loading process is wreaking havoc.
Here's the source:

```
10 SCREEN 128
40 X(1)=159:Y(1)=0
50 X(2)=0:Y(2)=199
60 X(3)=319:Y(3)=199
70 X=X(1):Y=Y(1)
80 D=RND(1)*3+1
90 X=X/2+X(D)/2
100 Y=Y/2+Y(D)/2
110 PSET X,Y,D+2
120 GOTO 80
```
[SIERPINSKI.PRG.zip](https://github.com/commanderx16/x16-rom/files/8600966/SIERPINSKI.PRG.zip)

**Comment by kelli217** [comment]
Thanks!
