### ISSUE TITLE
-keymap command line argument does not select the correct keymap

### ISSUE THREAD

**Issue by megagrump** [commanderx16/x16-emulator#402]
`./x16emu -keymap <any keymap>` does not activate the selected keymap. For example: `-keymap it` selects the `de` keymap.

![image](https://user-images.githubusercontent.com/31128870/169640447-e85953bf-b761-4769-919b-eac33a823d27.png)

Tested in r41 (Marrakech) on Linux x86-64.

**Comment by indigodarkwolf** [comment]
Should be fixed with #403, but see new issue #406
