### ISSUE TITLE
dos "cd:*" command doesn't work.

### ISSUE THREAD

**Issue by oshaboy** [commanderx16/x16-emulator#431]
I tried making a folder called "SOFTWARE" and typing `dos "cd:software"` to access it. The command doesn't give an error message but also doesn't change the working directory of the emulator. Attempted on both windows and linux.

**Comment by irmen** [comment]
Are you attempting to do this on the host filesystem? This only works on SD card images.

**Comment by oshaboy** [comment]
Yes I was, thank you. I will try to make an SD card image.
