### ISSUE TITLE
Generating chargen.bin

### ISSUE THREAD

**Issue by taybart** [commanderx16/x16-emulator#44]
### Version
`master`

### Env
```
$ uname -a
Darwin taybart.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```
### Expectation 
Demo `chargen.bin`
### Result
No info on generation of char set

Hello! I am very new to retro build systems. I was not able to find how the `chargen.bin` was built. Is this a cc64 thing? Or is this a custom character set that you guys have put together? I edited the wiki on "building from scratch on a Mac. I would love to do some more documentation as I go (sweeping up all the low hanging fruit I am sure) on at least linux and macOS.

**Comment by mobluse** [comment]
You can build chargen from this repository: https://github.com/mobluse/chargen-maker

**Comment by mist64** [comment]
I added instructions to the README. a6a1427
