### ISSUE TITLE
CINT + PLOT as first calls after startup (via `-prg program -run`) cause black home square

### ISSUE THREAD

**Issue by markjreed** [commanderx16/x16-emulator#449]
If I assemble this program and run it with `x16emu -prg filename -run`, the upper left corner character space turns black after the call to PLOT:

```
sys   = $9e
basic = $0801
cint  = $ff81
plot  = $fff0

.word basic
.org  basic
.word end
.word *
.byte sys, .sprintf("%d", *+7), 0
end:  .word 0

  jsr cint
  jmp plot
```

This does not occur if I leave off the `-run` and instead type `RUN` once at the READY prompt. So I suspect it's a race condition between the implementation of `-run` and the ROM's startup initialization.

**Comment by irmen** [comment]
I encountered this as well, and for what it's worth here is the "workaround" I came up with in prog8 / inline assembly:

```
asmsub fix_autostart_square() {
    ; Here's a possible work around for weird issue that prints a black character after first call to c64.PLOT()
    ; if you're also using c64.CINT() yourself. The default prog8 program initialization (which calls CINT) already performs this workaround.
    ; The problem occurs when a program is autostarded in the emulator with -run -prg test.prg,
    ; or when the program is saved as AUTOBOOT.X16 and loaded on boot like that.
    %asm {{
        phx
        sec
        jsr  c64.PLOT
        clc
        jsr  c64.PLOT
        lda  #' '
        jsr  c64.CHROUT     ; overwrite the black square
        clc
        jsr  c64.PLOT       ; cursor back to original position
        plx
        rts
    }}
}
```

**Comment by irmen** [comment]
Actually, this was resolved in https://github.com/commanderx16/x16-rom/pull/375

This issue can be closed I think.

**Comment by markjreed** [comment]
This does appear to be fixed in the latest ROM build. Closing.
