### ISSUE TITLE
How to stop a basic program?

### ISSUE THREAD

**Issue by johalun** [commanderx16/x16-emulator#46]
It's not really a thing to post here but I don't want to pollute the facebook group and I don't know if there's a IRC channel, gitter, discord or somewhere to chat about Commander X16.

What keys are mapped to RUN/STOP? How do I stop a basic program?

**Comment by indigodarkwolf** [comment]
I don't know if this is "RUN/STOP", but on Windows you can Ctrl-C to break back to the console. I'm not sure what the keybinding is on other platforms.

**Comment by johalun** [comment]
Not kill the emulator, just kill the running basic program...

**Comment by mobluse** [comment]
Run/Stop is Escape or Ctrl+C in the emulator. This web page could give some clues to the X16 keyboard, but AltLeft on X16 is the Win key on THEC64 Mini and Shift on X16 is often Alt on THEC64 Mini. https://retrogames.biz/thec64-mini/keyboard . X16 also uses the AltGr/AltRight as a modifier key for characters that could not otherwise be typed.

**Comment by 3vi1** [comment]
It would be nice if there were an additional warm-reset combo (or is that already a thing too?).  I tried the cc65-sprite demo and (in addition to not running properly) it hangs the emulator hard on exit here on Linux.

**Comment by indigodarkwolf** [comment]
Ctrl+R is the warm-reset combo.

I believe the cc65-sprite demo was using an interrupt to fix the timing of its sprite movement. Most likely, this needs to be updated for r30, which requires programs to reset the Vera interrupt register before returning control to the interrupted process.

**Comment by 3vi1** [comment]
@indigodarkwolf Thanks!  I put in an issue for the sprite demo in the related git project so it doesn't get forgotten.  I've only been playing with this thing for 45 minutes and I already love this project.

**Comment by indigodarkwolf** [comment]
I'm having a blast, as well. If you want a demo that I know works, I have a Matrix-like colored text crawl over at http://github.com/indigodarkwolf/x16-matriculate-text. I'm quite pleased that it was shown in Dave's latest video. But it's not a "trivial" demo, nor is it C, but I hope it's reasonably well-commented for being 6502 assembly.

**Comment by johalun** [comment]
Oh I see why none of my CTRL+xxx didnt' work.. I have ctrl mapped to caps lock in X11 and apparently, SDL is reading raw key codes so I have to use the actual ctrl key :(

**Comment by indigodarkwolf** [comment]
Yes, that is intentional because the X16 will be acting on keyboards' actual scancodes, not their logical key assignment, due to the PS/2 interface.

**Comment by indigodarkwolf** [comment]
I've lost where the change went in, but I believe there was also a problem with some international keyboards not being able to express certain keys to the emulator. That was before the Facebook poll asking what keyboard layouts folks used, and subsequent work towards supporting those.

**Comment by mist64** [comment]
I have added some info like this to the new "BASIC and the Screen Editor" in the README.
