### ISSUE TITLE
RND(0) always seems to return 0

### ISSUE THREAD

**Issue by MCPEmaniac** [commanderx16/x16-emulator#48]
RND(0) always seems to return 0 on emulator perhaps because it's based on hardware that isn't present. Perhaps it should default to one of the other RND() options.

**Comment by rsbohn12** [comment]
This is a known issue, it will be fixed when the RTC is implemented.

**Comment by MCPEmaniac** [comment]
In that case I recommend adding it to the known issues on the release page.

**Comment by mist64** [comment]
The correct fix would be to implement VIA timers (VIA#1), but the workaround returns random numbers in VIA#1 registers 4,5,8,9. :)
