### ISSUE TITLE
Add 65C02 Opcodes

### ISSUE THREAD

**Issue by paulscottrobson** [commanderx16/x16-emulator#5]
I'll do it if you like.

**Comment by mist64** [comment]
The question whether it's worth adding (and debugging) the extra instructions, or whether it's a better idea to switch to a different CPU emulator that already supports it. I do like the license of fake6502 (public domain!), and I think it's super nice to interface, and very readable.

So if you don't mind going through all the work of adding the extra instructions, I would *love* to see the 65C02 instructions implemented!

**Comment by paulscottrobson** [comment]
This is a first go, it's not tested, except by running MS Basic (obviously), and checking nothing has changed. I'll test it tomorrow properly.

The fake6502.c code has been modularised ; hence the "cpu" subdirectory. The subcomponents of the file have been subdivided, and an extra file 65c02.h has been added with the support code needed for that. fake6502.c now just includes the various subcomponents. Apart from the new 65c02.h file it's unchanged (except BRK, see below).

The table file is now generated from a list of opcodes (2, actually, one is the 65C02 extensions), which makes updates and changes much easier and less error prone. I back checked that it's the same table as the original allowing for nop cycles and similar in the original, which are all wrong anyway.

There are several other changes to be made. These actually make it more accurate. BRK now clears the Decimal Flag, and ADC/SBC work differently in Decimal mode. Some of the wrapround fixes don't apply any more. The emulator had a wierd superfluous second subtract immediate (EB), and the undocumented opcodes have been removed (they are all NOPs now). The original did not do r-m-w opcodes correctly (a 6502 writes the original value, then the new value). Fortunately the 65C02 doesn't do this. This corrects a potential bug if some strange person wants to rol those addresses. 

All these are a more accurate reflection of the 65C02.  The only potential breaking change is the BRK/Decimal flag.

I should be able to automatically generate disasm.c from the CPU descriptor with a bit of luck. Haven't tried it.

[fix16.zip](https://github.com/commanderx16/x16-emulator/files/3571532/fix16.zip)

**Comment by paulscottrobson** [comment]
Tested version.
[65C02.zip](https://github.com/commanderx16/x16-emulator/files/3574377/65C02.zip)

**Comment by paulscottrobson** [comment]
Tested version. 
[65C02.zip](https://github.com/commanderx16/x16-emulator/files/3574379/65C02.zip)
