### ISSUE TITLE
Bug: -run flag doesn't run PRG correctly if no parenthesis around SYS2061

### ISSUE THREAD

**Issue by dansalvato** [commanderx16/x16-emulator#57]
This sounds weird, but I'll try my best to explain. If my program starts with `10 SYS(2061)` then I can run it both with the emulator's `-run` flag, as well as with the BASIC command `RUN`, as expected.

However, if my program starts with `10 SYS2061` (plus two padding bytes to replace the parentheses), I can use `RUN` just fine. But if I use `-run`, the program runs, but I get different behavior. In my case, I think something in my VSYNC interrupt routine fails to return.

In the readme, I see `-run` described like this:

>same as above [-prg], but also executes the application using RUN or SYS, depending on the load address.

This makes me wonder if `-run` will only execute using `RUN` if it sees the parentheses in the `SYS` BASIC line? That's the extent to which I can speculate.

Side note: It seems `-run` is not a replacement for `-prg` as the readme suggests, but must be used in conjunction with it, eg. `-prg test.prg -run`.

**Comment by mist64** [comment]
Fixed the documentation of -run in the REAMDE in ef36000.

The emulator injects "RUN"+CR into the keyboard queue if the program was loaded  to $0801. Do you have an example .prg that shows the behavior you are describing?

**Comment by dansalvato** [comment]
Sure, here you go. The sprite will animate when manually typing `RUN` but will not if the `-run` flag is used.

[test.zip](https://github.com/commanderx16/x16-emulator/files/3613374/test.zip)

**Comment by mist64** [comment]
I just tried it with
* LOAD"TEST.PRG; RUN
* -prg test.prg; RUN
* -prg test.prg -run
And in all three cases, I see a sprite, but it doesn't animate.

This is on the latest source. What version were you testing it with?

**Comment by dansalvato** [comment]
I see, I was testing it on the r30 release, I apologize for not specifying. I heard some VERA memory addresses have changed since then, but I don't know the full details.

**Comment by mist64** [comment]
I could confirm the issue on r30. I tried comparing traces on the current version, but I don't see a difference. Can you port your code to work with the new version? (I can email you a build, if you tell me your host OS.)

**Comment by dansalvato** [comment]
Sure, thank you for offering to build for me, as I don't have the dev environment set up for it. I'm on Windows 10.

Happy to port to the new version as long as VERA 0.8 is not still ongoing active changes, as that was my plan once r31 was released.

**Comment by greg-king5** [comment]
"It works for me."

I used release 30 on Windows 8.1

**Comment by mist64** [comment]
@dansalvato I sent you an email.

**Comment by dansalvato** [comment]
The issue was user error. I didn't realize VERA interrupts were enabled by default, so an interrupt was being triggered before my program was done initializing. This caused arbitrarily different behaviors depending on how far along the program got before the first VERA interrupt, making it look like some kind of emulator bug. I'm glad it's not, and I got my program fully working on r31+ as well.
