### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by oaguy1** [commanderx16/x16-emulator#66]
Hello! Would you guys be open to adding an open source license such as GPL3 or MIT? It would ensure the project is here to stay and that people’s contributions won’t be taken offline.

**Comment by mist64** [comment]
The README and most source files say it's 2-clause BSD. Some source files might have a different license.

**Comment by oaguy1** [comment]
Would it be okay if I made a PR with the BSD 2-Clause license added to the
repo as the LICENSE file?

**Comment by mist64** [comment]
Sure!
