### ISSUE TITLE
Chargen is now in rom.bin

### ISSUE THREAD

**Issue by rsbohn12** [commanderx16/x16-emulator#67]
cef98b538fb937af897b22e27368ffda9644ed9d removed the -chargen startup flag.
d27f32a44485b8911d1500dedf67d038ec755835 Vera 0.8 expects the chargen to be loaded into Vera by the kernal.

So if you're trying to run from master you'll need a new rom.bin.

Not really a bug, just hoping to avoid some confusion. This can be closed 2019-09-22.

**Comment by rsbohn** [comment]
This can now be closed.

**Comment by rsbohn12** [comment]
Thanks.
