### ISSUE TITLE
Open the WIKI for documentation

### ISSUE THREAD

**Issue by rsbohn12** [commanderx16/x16-emulator#7]
Lots of documentation, hints and tips appearing in the Facebook group. The Github wiki for this project could provide a long-term home for community provided documentation.

**Comment by msx80** [comment]
Yeah, on facebook they disappear quickly. I second this.

**Comment by mist64** [comment]
I created the Wiki. Anything else I need to do?

**Comment by rsbohn12** [comment]
It looks like you can allow anyone with a GitHub account to edit the wiki, or restrict it to project collaborators. Not sure how you will want to handle that.

**Comment by mist64** [comment]
I enabled the wiki for everyone, I think. Can you try?

**Comment by rsbohn12** [comment]
Just added a 'Getting Started' page. Looks good!
