### ISSUE TITLE
Error when running make after latest commit

### ISSUE THREAD

**Issue by jjbliss** [commanderx16/x16-emulator#77]
after commit fa918305bda9197407cc7e5ebd2f93770188763b 
I now get an error when running make.
I have tested this on both Mac and Linux.  The error does not occur on earlier commits.

main.c:63:10: fatal error: 'rom_labels.h' file not found
#include "rom_labels.h"
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [main.o] Error 1

**Comment by mist64** [comment]
Thanks. Fixed in 56ac22e.
