### ISSUE TITLE
Build fails on CentOS 7

### ISSUE THREAD

**Issue by blackknight36** [commanderx16/x16-emulator#78]
Building the emulator fails on CentOS 7 due to undeclared variables in the for loops.  For example, running make results in several errors such as this.

```c
c -O3 -Wall -Werror -g -I/usr/include/SDL2 -D_REENTRANT -c video.c -o video.o
In file included from video.c:11:0:
gif.h: In function ‘GifPartition’:
gif.h:167:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int ii = left; ii < right - 1; ++ii) {
   ^
gif.h:167:3: note: use option -std=c99 or -std=gnu99 to compile your code
```
After adding -std=c99 to the CFLAGS I then get another error.

```
09:59 $ make
cc -std=c99 -O3 -Wall -Werror -g -I/usr/include/SDL2 -D_REENTRANT -c main.c -o main.o
main.c: In function ‘main’:
main.c:230:21: error: ‘PATH_MAX’ undeclared (first use in this function)
  char rom_path_data[PATH_MAX];
                     ^
main.c:230:21: note: each undeclared identifier is reported only once for each function it appears in
main.c:586:5: error: implicit declaration of function ‘usleep’ [-Werror=implicit-function-declaration]
     usleep(1000 * diff_time);
     ^
main.c:230:7: error: unused variable ‘rom_path_data’ [-Werror=unused-variable]
  char rom_path_data[PATH_MAX];
       ^
cc1: all warnings being treated as errors
make: *** [main.o] Error 1
```

How can I resolve this?  I was able to build the ROM without an issue however I'm not sure where the emulator expects the file to be located.

**Comment by mist64** [comment]
* `-std=c99` in CFLAGS sounds like the correct solution
* For `PATH_MAX`, try `#include <limits.h>`
* For `usleep`, try `#include <unistd.h>`
* For `rom_path_data`, I don't know, it's clearly used...

**Comment by blackknight36** [comment]
Looking through the code it appears the compiler is correct.  PATH_MAX is never defined anywhere.

```
10:15 $ rg PATH_MAX
main.c
230:    char rom_path_data[PATH_MAX];
232:    char char_path_data[PATH_MAX];
252:            strncpy(rom_path, argv[0], PATH_MAX);
253:            strncpy(rom_path + strlen(rom_path), rom_filename, PATH_MAX - strlen(rom_path));
255:            strncpy(char_path, argv[0], PATH_MAX);
256:            strncpy(char_path + strlen(char_path), char_filename, PATH_MAX - strlen(char_path));
261:            strncpy(rom_path, rom_filename + 1, PATH_MAX);
263:            strncpy(char_path, char_filename + 1, PATH_MAX);
```
I can update the code to define a value however that raises the question of what *should* the value be defined as?

**Comment by blackknight36** [comment]
I found a solution after making a few changes.  See this commit for details.

https://github.com/blackknight36/x16-emulator/commit/410f1dfb9e4fe6a62f328f76058d33340641c2d1

I'd be happy to open a pull request if you'd like to merge these in.

**Comment by mist64** [comment]
Yes, pull request please!

**Comment by blackknight36** [comment]
@mist64 Is there an ifdef we could use to detect if the build is running on Linux?  Something like #ifdef LINUX ?
