### ISSUE TITLE
LOAD command case sensitivity

### ISSUE THREAD

**Issue by blackknight36** [commanderx16/x16-emulator#79]
Would it be possible to make the LOAD command in basic case insensitive?  I just noticed that trying to load a file with a lowercase name fails in the emulator.  For example, trying to load a file name "test.prg" will fail but "TEST.PRG" works fine.

**Comment by Kroc** [comment]
How would this work on Linux, which usually defaults to a case-sensitive file-system?

**Comment by blackknight36** [comment]
@Kroc, good question, that's why I ran into this issue in the first place.  :D

I guess the best solution would just be to rename my files.

**Comment by greg-king5** [comment]
What's needed is proper conversion between ASCII and PetSCII.  It will solve the directory listing problem also.
