### ISSUE TITLE
Missing window title on Linux

### ISSUE THREAD

**Issue by blackknight36** [commanderx16/x16-emulator#82]
When running the emulator on Linux there is no window title defined.  Attached is a screenshot for reference.

![Screenshot_2019-09-18_17-43-27](https://user-images.githubusercontent.com/18019703/65188204-dd2ab500-da3b-11e9-8e1c-02054b27b3a5.png)

**Comment by lgblgblgb** [comment]
Missing SDL_SetWindowTitle() call maybe? Preferably with SDL_SetWindowIcon as well, to have some icon to shine ;)

**Comment by blackknight36** [comment]
@lgblgblgb Is there a copy of the Commander X16 logo available as a 16x16 bitmap?  I've been able to get a window icon defined however right now I'm using the default SDL pixel data as shown in the attached screenshot.

![Screenshot_2019-09-19_11-46-52](https://user-images.githubusercontent.com/18019703/65259872-650fce00-dad3-11e9-845a-466fc4fdc19b.png)

**Comment by lgblgblgb** [comment]
I'm not so much any insider of X16 development, so I don't have. I just try to help here and there with some tips, in the hope that those hints can help, that's all :(
