### ISSUE TITLE
Null pointer dereference in sdcard.c without specified -sdcard CLI option

### ISSUE THREAD

**Issue by lgblgblgb** [commanderx16/x16-emulator#88]
Without using -sdcard CLI option, sdcard_files (type: FILE*)  - initialized to be NULL porinter in spi.c - remains NULL. There is a check in main.c if file given by -sdard CLI option can opened, though if you don't use it, that check won't mean anything. Later in sdcard.c though uses sdcard_files to fseek, fread and such.

So, if you don't use -sdcard CLI option, the first time, something want to access the SD-card (for me, I wanted to do: DOS"$" ...) there will be a null pointer deference on fseek() implementation in libc, and the emulator will segfault.

**Comment by mist64** [comment]
8597ec9
