### ISSUE TITLE
[Windows] LOAD

### ISSUE THREAD

**Issue by phaax** [commanderx16/x16-emulator#9]
Here's a video of the issue I'm having: https://youtu.be/e832Mj02oak

On the right is the file I'm loading opened in a hex editor.
Notice how everything turns blue when I try to manually fix the loaded code.

**Comment by Pandamad** [comment]
I have the same issue if I try and LOAD a text file containing BASIC code stored as TEXT.
CR and LF characters are ignored also. I think it is expecting a tokenised format, not ANSI text.

**Comment by paulscottrobson** [comment]
Yes it is. Try something like this https://github.com/catseye/hatoucan and use the -prg option to load it. It will not work for VPEEK/VPOKE/MON and any other new keywords. These appear to be tokenised with a 2 byte sequence which would require some modification.

**Comment by phaax** [comment]
> Yes it is. Try something like this https://github.com/catseye/hatoucan and use the -prg option to load it. It will not work for VPEEK/VPOKE/MON and any other new keywords. These appear to be tokenised with a 2 byte sequence which would require some modification.

I was trying to load a text file because the emulator didn't work with my keyboard layout. I thought I was being clever, but I didn't realize that tokenization was a thing. :)

Thanks! I'm gonna write my own tokenizer and learn more about it. Very interesting!

**Comment by mist64** [comment]
You can use https://github.com/mist64/cbmbasic for tokenizing and detokenizing:
* tokenize by running cbmbasic and pasting the BASIC program (in upper case), then use the `SAVE` command to save the tokenized program.
* detokenize by running cbmbasic, using the `LOAD` command to load the tokenized program and show it with `LIST`.
