### ISSUE TITLE
Hex format not supported in DATA statements

### ISSUE THREAD

**Issue by MCPEmaniac** [commanderx16/x16-emulator#92]
Execution of the following Basic program causes ?SYNTAX  ERROR IN 30.
10 READ A
20 STOP
30 DATA $50
Sorry about that. I just noticed it in the Known Issues section of the Code tab but there doesn't seem to be a way to delete this entry. I originally looked at KERNAL-BASIC.html, Programmer's Reference Guide.html, and README.html which don't seem to mention the issue.

**Comment by mist64** [comment]
This is already fixed in the source and will be part of release r31
