### ISSUE TITLE
[RFC] Better support for automated testing

### ISSUE THREAD

**Issue by hasenbanck** [commanderx16/x16-emulator#93]
I would like to get some feedback about some ideas about automated testing with the help of the emulator. Essentially I want to be able to run small PRGs against the emulator and check the "output" they create. Output could either mean the console output (we already have "echo" over STDOUT for that) and the memory content (CPU registers, RAM, RAM-banks, VRAM). The emulator should be able to exit after reaching a specified state and return the output.

I would like to implement following changes myself:

1. Either make the current behavior of reaching "$FFFF" in the PC, creating a memory dump and exiting a documented behavior, or create a new / alter an existing opcode to do the same (like the special $FF debug opcode with the help of a special command line argument).

2. Extend the current way of dumping of memory (```memory_save()```) so that we could choose which kind of dump to create (like "-log"). A special "-dump" command line argument would be needed to be able to configure this behavior. Right now I would add the following options (combinations are possible, like with "-log"):
- CPU-Registers
- RAM
- RAM-banks
- VRAM

**Comment by tobier** [comment]
Just regular unit tests on he codebase with good coverage would be splendid in my book :+1:

**Comment by hasenbanck** [comment]
@tobier This PR is not about testing the codebase of the emulator, but using the emulator to run tests for your own PRGs automatically.

**Comment by tobier** [comment]
@hasenbanck Ahh, sorry. But yes, this would also be very useful. Imagine having automated tests for your games on a Commodore 64 :smile:

**Comment by Kroc** [comment]
> @hasenbanck Ahh, sorry. But yes, this would also be very useful. Imagine having automated tests for your games on a Commodore 64 😄

It exists! https://64bites.com/64spec/

**Comment by christo** [comment]
Love this idea @hasenbanck 

I suggest having a way to make the emulator exit on basic "end" or have the ability to specify a trigger for exiting with mem dump. $ffff is good but ideally the production code does not need to be modified to make it testable.

Also, enabling automation of the console input/output for a running emulator could be made easier to work with. 

In addition to the testing of software running in the emulator, I think a test suite of software running on the fully integrated emulator would be very useful for making sure the emulator itself works (in addition to unit tests which @tobier mentioned).

**Comment by hasenbanck** [comment]
Since my PR was merged I think this issue is resolved.

I made a very simple testframework to show, how to use x16emu for automated tests (C and ASM based projects):
https://github.com/hasenbanck/x16-testframework

Better documentation will be added in due time.
