### ISSUE TITLE
Missing documents in release 31

### ISSUE THREAD

**Issue by greg-king5** [commanderx16/x16-emulator#96]
The contents of the VERA document replaced the contents of _Programmer's Reference Guide.html_.

P.S., You should put "rom.txt" into the "docs/" subdirectory.

**Comment by Kroc** [comment]
rom.txt is not documentation in that sense, it's a symbol file -- it's file extension should better represent this, being ".sym", or ".ll" if it's a VICE symbols file.

**Comment by greg-king5** [comment]
A symbols file **is** documentation!  It documents the values of symbols.  It isn't used by the execution of the program,  Therefore, it doesn't belong in the execution directory.

**Comment by Kroc** [comment]
symbol files belong with the file they are symbols for -- this is often how debuggers load symbols automatically! It's not user-documentation, which a "docs" directory is for.

**Comment by mist64** [comment]
I've fixed the release files:
* programmer's reference guide is added.
* rom.txt has been renamed to rom.sym
ca66b38

**Comment by greg-king5** [comment]
> Symbol files belong with the file they are symbols for -- this is often how debuggers load symbols automatically! It's not user-documentation, which a "docs" directory is for.

That's my point!  "rom.sym" _isn't_ for the emulator.  It describes the Kernal and the BASIC interpreter.  It belongs with the _other_ files that do the same thing.

**Comment by Kroc** [comment]
rom.bin is in the root (in binary releases), where the exe expects it. Therefore that's where rom.sym has to go.

**Comment by greg-king5** [comment]
> "rom.bin" is in the root (in binary releases), where the exe expects it. Therefore, that's where "rom.sym" has to go.

That would be true _if_ "rom.sym" was used _with_ "rom.bin"; but it isn't -- the executable doesn't do anything with it, at all.

Again ... "rom.bin" is for the execution of the emulator; but, "rom.sym" isn't -- it's for us!  When we write programs, we refer to _Programmer's Reference Guide.html_, _VERA Programmer's Reference.html_, and _rom.sym_.  All three files should be in the same place.  It's what we want.  We expect the reference material to be together -- it's easier to find, that way.
